#include "FactoryPresets.h"
#include "../parameters/ParameterIds.h"

namespace sappsynth::presets {
namespace p = sappsynth::param;

const std::vector<Preset>& all()
{
    static const std::vector<Preset> bank {
        { "Init", "INIT", {} },

        // ================= BASS =================
        { "Acid Bass", "BASS", { { p::cutoff, 240 }, { p::resonance, 0.88f }, { p::filterEnvAmt, 0.75f },
            { p::filtDecay, 0.18f }, { p::filtSustain, 0 }, { p::keyTrack, 0.8f }, { p::filterDrive, 10 },
            { p::subLevel, 0.4f }, { p::ampDecay, 0.3f }, { p::ampRelease, 0.12f }, { p::polyphony, 1 },
            { p::filterVel, 0.6f }, { p::glide, 0.06f }, { p::delayMix, 0.22f }, { p::delayTime, 0.19f },
            { p::delayFeedback, 0.45f } } },
        { "Model Growl", "BASS", { { p::osc2Level, 0.9f }, { p::osc2Fine, -8 }, { p::subLevel, 0.6f },
            { p::cutoff, 350 }, { p::resonance, 0.25f }, { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.25f },
            { p::filtSustain, 0.1f }, { p::keyTrack, 0.4f }, { p::mixerDrive, 3.5f }, { p::filterDrive, 8 },
            { p::character, 0.8f }, { p::polyphony, 1 }, { p::glide, 0.04f }, { p::ampRelease, 0.2f } } },
        { "Taurus Rumble", "BASS", { { p::osc1Octave, -1 }, { p::subOctave, 1 }, { p::subLevel, 0.8f },
            { p::cutoff, 200 }, { p::mixerDrive, 3 }, { p::outputDrive, 6 }, { p::polyphony, 1 },
            { p::glide, 0.08f }, { p::ampRelease, 0.4f }, { p::character, 0.9f }, { p::filterEnvAmt, 0.3f },
            { p::filtDecay, 0.4f } } },
        { "Velvet Bass", "BASS", { { p::osc1Wave, 3 }, { p::subLevel, 0.7f }, { p::cutoff, 380 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.3f }, { p::ampDecay, 0.4f }, { p::ampSustain, 0.6f },
            { p::dnaWarmth, 0.7f }, { p::character, 0.7f }, { p::polyphony, 1 } } },
        { "Rubber Bass", "BASS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 12 },
            { p::osc2Fm, 0.28f }, { p::osc2Level, 0 }, { p::cutoff, 650 }, { p::filterEnvAmt, 0.5f },
            { p::filtDecay, 0.16f }, { p::filtSustain, 0 }, { p::ampDecay, 0.35f }, { p::filterVel, 0.6f },
            { p::polyphony, 1 }, { p::subLevel, 0.4f } } },

        // ================= LEAD =================
        { "Fat Fifth Lead", "LEAD", { { p::osc2Semi, 7 }, { p::osc2Level, 0.9f }, { p::cutoff, 2500 },
            { p::resonance, 0.3f }, { p::polyphony, 1 }, { p::glide, 0.05f }, { p::character, 0.7f },
            { p::delayMix, 0.25f }, { p::unisonCount, 2 }, { p::unisonDetune, 8 }, { p::filterVel, 0.4f } } },
        { "Lucky Lead", "LEAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 6 }, { p::unisonCount, 3 },
            { p::unisonDetune, 10 }, { p::cutoff, 1800 }, { p::filterEnvAmt, 0.4f }, { p::filterVel, 0.5f },
            { p::ampDecay, 0.5f }, { p::delayMix, 0.2f }, { p::character, 0.6f } } },
        { "Hoover Rave", "LEAD", { { p::osc2Wave, 2 }, { p::osc2Pw, 0.4f }, { p::osc2Level, 0.9f },
            { p::unisonCount, 5 }, { p::unisonDetune, 35 }, { p::unisonSpread, 1 }, { p::cutoff, 3000 },
            { p::glide, 0.15f }, { p::chorusMix, 0.4f }, { p::ampAttack, 0.02f }, { p::character, 0.6f },
            { p::polyphony, 10 } } },
        { "Whistle (Self-Osc)", "LEAD", { { p::osc1Level, 0 }, { p::noiseLevel, 0.06f }, { p::cutoff, 880 },
            { p::resonance, 1 }, { p::keyTrack, 1 }, { p::filterEnvAmt, 0 }, { p::ampAttack, 0.02f },
            { p::ampRelease, 0.5f }, { p::quality, 2 }, { p::reverbMix, 0.35f } } },
        { "Silver Flute", "LEAD", { { p::osc1Wave, 0 }, { p::noiseLevel, 0.05f }, { p::cutoff, 2600 },
            { p::keyTrack, 1 }, { p::ampAttack, 0.06f }, { p::ampRelease, 0.3f }, { p::lfoRate, 5.5f },
            { p::lfoToPitch, 6 }, { p::polyphony, 1 }, { p::glide, 0.03f }, { p::reverbMix, 0.25f } } },
        { "Solina Glide", "LEAD", { { p::osc1Wave, 1 }, { p::osc2Level, 0.85f }, { p::osc2Fine, 4 },
            { p::cutoff, 2000 }, { p::glide, 0.09f }, { p::polyphony, 1 }, { p::chorusMix, 0.5f },
            { p::character, 0.8f }, { p::ampRelease, 0.4f }, { p::delayMix, 0.2f } } },

        // ================= KEYS =================
        { "Juno Chorus Keys", "KEYS", { { p::subLevel, 0.5f }, { p::cutoff, 4500 }, { p::ampAttack, 0.01f },
            { p::ampDecay, 0.4f }, { p::ampSustain, 0.6f }, { p::chorusMix, 0.6f }, { p::character, 0.6f },
            { p::filterVel, 0.4f }, { p::ampRelease, 0.3f } } },
        { "Vintage Organ", "KEYS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.5f }, { p::subWave, 1 }, { p::subLevel, 0.8f }, { p::cutoff, 8000 },
            { p::ampAttack, 0.005f }, { p::ampSustain, 1 }, { p::ampRelease, 0.06f }, { p::chorusMix, 0.3f } } },
        { "Punchy Pluck", "KEYS", { { p::osc2Wave, 2 }, { p::osc2Semi, -12 }, { p::osc2Level, 0.6f },
            { p::cutoff, 900 }, { p::resonance, 0.35f }, { p::filterEnvAmt, 0.8f }, { p::filtDecay, 0.12f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.35f }, { p::ampSustain, 0 }, { p::ampRelease, 0.25f },
            { p::keyTrack, 1 }, { p::filterVel, 0.6f }, { p::delayMix, 0.18f } } },
        { "Warm Brass", "KEYS", { { p::osc2Level, 0.85f }, { p::osc2Fine, 4 }, { p::cutoff, 750 },
            { p::resonance, 0.15f }, { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.35f }, { p::filtSustain, 0.4f },
            { p::ampAttack, 0.04f }, { p::ampRelease, 0.3f }, { p::mixerDrive, 2.2f }, { p::character, 0.7f },
            { p::chorusMix, 0.2f }, { p::reverbMix, 0.18f } } },
        { "Poly Comp Stab", "KEYS", { { p::osc2Wave, 2 }, { p::osc2Level, 0.8f }, { p::cutoff, 1600 },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.2f }, { p::filtSustain, 0.1f }, { p::ampDecay, 0.3f },
            { p::ampSustain, 0.2f }, { p::ampRelease, 0.2f }, { p::filterVel, 0.7f }, { p::chorusMix, 0.25f } } },
        { "Church Organ", "KEYS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0.35f }, { p::subWave, 1 }, { p::subLevel, 0.9f }, { p::cutoff, 6000 },
            { p::ampAttack, 0.03f }, { p::ampSustain, 1 }, { p::ampRelease, 0.4f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.95f } } },

        // ================= FM =================
        { "FM E-Piano", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.35f }, { p::cutoff, 8000 }, { p::ampDecay, 0.8f },
            { p::ampSustain, 0.3f }, { p::ampRelease, 0.4f }, { p::filterVel, 0.5f }, { p::reverbMix, 0.15f },
            { p::chorusMix, 0.25f } } },
        { "FM Bells", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Fine, 30 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.5f }, { p::cutoff, 12000 },
            { p::ampAttack, 0.005f }, { p::ampDecay, 1.5f }, { p::ampSustain, 0 }, { p::ampRelease, 1.5f },
            { p::reverbMix, 0.4f }, { p::reverbSize, 0.7f } } },
        { "Glass Clang", "FM", { { p::osc1Wave, 3 }, { p::osc2Wave, 2 }, { p::osc2Octave, 1 }, { p::osc2Semi, 6 },
            { p::osc2Level, 0.2f }, { p::osc2Fm, 0.7f }, { p::mixerDrive, 2 }, { p::cutoff, 9000 },
            { p::ampDecay, 0.6f }, { p::ampSustain, 0 }, { p::ampRelease, 0.5f }, { p::delayMix, 0.3f } } },
        { "Metal Drone", "FM", { { p::osc2Octave, -1 }, { p::osc2Fine, 13 }, { p::osc2Level, 0.5f },
            { p::osc2Fm, 0.9f }, { p::resonance, 0.5f }, { p::cutoff, 1200 }, { p::character, 1 },
            { p::driftAmount, 4 }, { p::reverbMix, 0.5f }, { p::ampAttack, 0.5f }, { p::ampRelease, 2 },
            { p::quality, 2 } } },
        { "Wurli Bite", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.42f }, { p::mixerDrive, 3 }, { p::dnaWarmth, 0.8f },
            { p::cutoff, 5000 }, { p::ampDecay, 0.6f }, { p::ampSustain, 0.4f }, { p::filterVel, 0.7f },
            { p::delayMix, 0.15f } } },
        { "Sunken Bells", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.45f }, { p::cutoff, 4000 }, { p::ampAttack, 0.01f },
            { p::ampDecay, 2 }, { p::ampSustain, 0 }, { p::ampRelease, 2.5f }, { p::reverbMix, 0.65f },
            { p::reverbSize, 0.9f }, { p::delayMix, 0.3f }, { p::delayTime, 0.6f }, { p::delayFeedback, 0.55f } } },

        // ================= PAD =================
        { "Drift Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 9 }, { p::subLevel, 0.5f },
            { p::cutoff, 1600 }, { p::ampAttack, 0.6f }, { p::ampRelease, 1.2f }, { p::filtAttack, 0.8f },
            { p::filterEnvAmt, 0.3f }, { p::character, 1 }, { p::driftAmount, 4 }, { p::warmup, 0.4f },
            { p::quality, 2 }, { p::reverbMix, 0.42f }, { p::reverbSize, 0.8f }, { p::delayMix, 0.18f } } },
        { "Jupiter Sweep Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 5 }, { p::osc1Fine, -5 },
            { p::cutoff, 900 }, { p::lfoToCutoff, 0.35f }, { p::lfoRate, 0.15f }, { p::ampAttack, 0.8f },
            { p::ampRelease, 1.6f }, { p::chorusMix, 0.45f }, { p::reverbMix, 0.35f }, { p::character, 0.8f },
            { p::polyphony, 16 }, { p::unisonCount, 2 }, { p::unisonDetune, 9 } } },
        { "PWM Strings", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.32f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.68f }, { p::osc2Fine, -6 }, { p::osc2Level, 0.8f }, { p::cutoff, 3800 },
            { p::ampAttack, 0.25f }, { p::ampRelease, 0.8f }, { p::lfoRate, 0.8f }, { p::lfoToPitch, 3 },
            { p::character, 0.8f }, { p::chorusMix, 0.5f }, { p::reverbMix, 0.3f } } },
        { "Polysix Strings", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.65f }, { p::osc2Fine, -4 }, { p::osc2Level, 0.85f }, { p::cutoff, 3200 },
            { p::ampAttack, 0.35f }, { p::ampRelease, 1 }, { p::chorusMix, 0.55f }, { p::reverbMix, 0.25f },
            { p::lfoToPitch, 2 }, { p::lfoRate, 0.7f } } },
        { "Super Saw Stack", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, -7 }, { p::unisonCount, 5 },
            { p::unisonDetune, 22 }, { p::unisonSpread, 0.9f }, { p::cutoff, 5200 }, { p::ampAttack, 0.02f },
            { p::ampRelease, 0.5f }, { p::chorusMix, 0.25f }, { p::reverbMix, 0.22f }, { p::polyphony, 16 } } },
        { "Tape Flute", "PAD", { { p::osc1Wave, 0 }, { p::noiseLevel, 0.05f }, { p::cutoff, 3000 },
            { p::glide, 0.12f }, { p::character, 1 }, { p::driftAmount, 5 }, { p::warmup, 0.6f },
            { p::ampAttack, 0.08f }, { p::reverbMix, 0.3f }, { p::polyphony, 1 } } },
        { "Glacier Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 6 }, { p::cutoff, 1200 },
            { p::ampAttack, 1.2f }, { p::ampRelease, 2.5f }, { p::reverbMix, 0.6f }, { p::reverbSize, 0.9f },
            { p::chorusMix, 0.3f }, { p::character, 0.8f }, { p::driftAmount, 3 }, { p::polyphony, 16 } } },
        { "Analog Choir", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.45f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.55f }, { p::osc2Fine, 4 }, { p::osc1Fine, -4 }, { p::osc2Level, 0.9f },
            { p::cutoff, 2000 }, { p::chorusMix, 0.6f }, { p::ampAttack, 0.5f }, { p::ampRelease, 1.5f },
            { p::unisonCount, 2 }, { p::unisonDetune, 7 }, { p::reverbMix, 0.4f } } },
        { "Dark Cathedral", "PAD", { { p::osc1Octave, -1 }, { p::subOctave, 1 }, { p::subLevel, 0.7f },
            { p::cutoff, 700 }, { p::resonance, 0.3f }, { p::ampAttack, 0.8f }, { p::ampRelease, 3 },
            { p::reverbMix, 0.7f }, { p::reverbSize, 1 }, { p::character, 0.8f }, { p::delayMix, 0.2f },
            { p::delayTime, 0.8f } } },
        { "Warm Tape Pad", "PAD", { { p::osc1Wave, 3 }, { p::osc2Wave, 3 }, { p::osc2Fine, 8 },
            { p::osc2Level, 0.9f }, { p::dnaWarmth, 0.9f }, { p::dnaAge, 0.6f }, { p::character, 1 },
            { p::driftAmount, 5 }, { p::driftSpeed, 0.4f }, { p::cutoff, 1500 }, { p::chorusMix, 0.4f },
            { p::ampAttack, 0.6f }, { p::ampRelease, 2 } } },
        { "Widescreen", "PAD", { { p::unisonCount, 4 }, { p::unisonDetune, 14 }, { p::unisonSpread, 1 },
            { p::osc2Level, 0.85f }, { p::cutoff, 2400 }, { p::ampAttack, 0.7f }, { p::ampRelease, 2 },
            { p::chorusMix, 0.35f }, { p::reverbMix, 0.4f }, { p::polyphony, 16 } } },

        // ================= AMBIENT =================
        { "Aurora Swell", "AMBIENT", { { p::osc1Wave, 3 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.7f },
            { p::osc2Fine, 5 }, { p::lfoToCutoff, 0.3f }, { p::lfoRate, 0.07f }, { p::cutoff, 1100 },
            { p::ampAttack, 1.5f }, { p::ampRelease, 3 }, { p::delayMix, 0.3f }, { p::delayTime, 0.7f },
            { p::delayFeedback, 0.6f }, { p::reverbMix, 0.5f }, { p::reverbSize, 0.9f } } },
        { "Shimmer Drift", "AMBIENT", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0.5f }, { p::osc2Fm, 0.15f }, { p::cutoff, 6000 }, { p::ampAttack, 1 },
            { p::ampRelease, 3 }, { p::reverbMix, 0.65f }, { p::reverbSize, 0.95f }, { p::driftAmount, 4 },
            { p::character, 0.9f } } },
        { "Evening Haze", "AMBIENT", { { p::cutoff, 900 }, { p::lfoToCutoff, 0.15f }, { p::lfoRate, 0.1f },
            { p::ampAttack, 1 }, { p::ampRelease, 2.5f }, { p::delayMix, 0.35f }, { p::delayTime, 0.9f },
            { p::delayFeedback, 0.65f }, { p::reverbMix, 0.45f }, { p::character, 0.8f } } },
        { "Slow Breath", "AMBIENT", { { p::noiseLevel, 0.15f }, { p::osc1Level, 0.6f }, { p::lfoShape, 1 },
            { p::lfoRate, 0.05f }, { p::lfoToCutoff, 0.4f }, { p::cutoff, 600 }, { p::ampAttack, 2 },
            { p::ampRelease, 3 }, { p::reverbMix, 0.5f }, { p::reverbSize, 0.9f } } },
        { "Static Field", "AMBIENT", { { p::noiseLevel, 0.4f }, { p::osc1Level, 0.3f }, { p::cutoff, 3000 },
            { p::resonance, 0.55f }, { p::lfoShape, 2 }, { p::lfoRate, 0.12f }, { p::lfoToCutoff, 0.3f },
            { p::ampAttack, 1 }, { p::ampRelease, 2 }, { p::reverbMix, 0.6f }, { p::dnaAge, 0.8f },
            { p::character, 1 } } },
        { "Hollow Reed", "AMBIENT", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.18f }, { p::cutoff, 1600 },
            { p::keyTrack, 1 }, { p::ampAttack, 0.3f }, { p::ampRelease, 1.5f }, { p::chorusMix, 0.25f },
            { p::reverbMix, 0.45f }, { p::reverbSize, 0.85f } } },

        // ================= ARP =================
        { "Berlin School", "ARP", { { p::arpMode, 3 }, { p::arpRate, 6 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.55f }, { p::subLevel, 0.4f }, { p::cutoff, 1100 }, { p::resonance, 0.45f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0.2f }, { p::delayMix, 0.35f },
            { p::delayTime, 0.375f }, { p::delayFeedback, 0.55f }, { p::ampRelease, 0.15f } } },
        { "Disco Octaves", "ARP", { { p::arpMode, 1 }, { p::arpRate, 9 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.4f }, { p::osc2Wave, 2 }, { p::osc2Semi, -12 }, { p::osc2Level, 0.6f },
            { p::cutoff, 1400 }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.12f }, { p::filtSustain, 0 },
            { p::ampSustain, 0.4f }, { p::ampRelease, 0.1f }, { p::delayMix, 0.2f } } },
        { "Dream Cascade", "ARP", { { p::arpMode, 3 }, { p::arpRate, 7.2f }, { p::arpOctaves, 2 },
            { p::arpGate, 0.6f }, { p::osc2Wave, 3 }, { p::osc2Level, 0.7f }, { p::cutoff, 1500 },
            { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.2f }, { p::filtSustain, 0 }, { p::ampSustain, 0.5f },
            { p::delayMix, 0.32f }, { p::delayTime, 0.42f }, { p::delayFeedback, 0.5f }, { p::reverbMix, 0.35f } } },
        { "Neon Nights", "ARP", { { p::arpMode, 1 }, { p::arpRate, 8.5f }, { p::arpGate, 0.5f },
            { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::cutoff, 1200 }, { p::resonance, 0.5f },
            { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.13f }, { p::filtSustain, 0.1f }, { p::ampSustain, 0.5f },
            { p::delayMix, 0.28f }, { p::delayTime, 0.33f }, { p::delayFeedback, 0.45f }, { p::chorusMix, 0.2f } } },
        { "Crystal Run", "ARP", { { p::arpMode, 4 }, { p::arpRate, 12 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.35f }, { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.5f }, { p::cutoff, 6000 }, { p::keyTrack, 1 }, { p::ampDecay, 0.15f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.2f }, { p::reverbMix, 0.45f }, { p::delayMix, 0.3f } } },
        { "Midnight Train", "ARP", { { p::arpMode, 2 }, { p::arpRate, 6 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.7f }, { p::subLevel, 0.6f }, { p::cutoff, 800 }, { p::resonance, 0.55f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.18f }, { p::ampSustain, 0.6f }, { p::delayMix, 0.4f },
            { p::delayTime, 0.375f }, { p::delayFeedback, 0.55f }, { p::character, 0.8f } } },
        { "Pluck & Bloom", "ARP", { { p::arpMode, 1 }, { p::arpRate, 5 }, { p::arpGate, 0.5f },
            { p::cutoff, 1000 }, { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.4f }, { p::ampSustain, 0 }, { p::ampRelease, 0.5f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.8f }, { p::delayMix, 0.35f }, { p::delayTime, 0.6f } } },
        { "Arcadia", "ARP", { { p::arpMode, 3 }, { p::arpRate, 9 }, { p::arpOctaves, 2 }, { p::arpGate, 0.45f },
            { p::osc1Wave, 2 }, { p::osc2Level, 0.8f }, { p::osc2Fine, 5 }, { p::cutoff, 1800 },
            { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.14f }, { p::ampSustain, 0.4f }, { p::chorusMix, 0.3f },
            { p::delayMix, 0.25f } } },
        { "Harp Machine", "ARP", { { p::arpMode, 1 }, { p::arpRate, 10 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.3f }, { p::osc1Wave, 3 }, { p::cutoff, 4000 }, { p::keyTrack, 1 },
            { p::ampDecay, 0.3f }, { p::ampSustain, 0 }, { p::ampRelease, 0.6f }, { p::reverbMix, 0.55f },
            { p::reverbSize, 0.85f } } },
        { "Berlin Sunrise", "ARP", { { p::arpMode, 3 }, { p::arpRate, 5.5f }, { p::arpOctaves, 3 },
            { p::arpGate, 0.6f }, { p::osc2Level, 0.85f }, { p::osc2Fine, 7 }, { p::cutoff, 1300 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.2f }, { p::ampSustain, 0.5f }, { p::delayMix, 0.45f },
            { p::delayTime, 0.5f }, { p::delayFeedback, 0.6f }, { p::driftAmount, 2 }, { p::character, 0.7f } } },
        { "Gamelan Steps", "ARP", { { p::arpMode, 4 }, { p::arpRate, 9 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.4f }, { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 17 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.5f }, { p::cutoff, 8000 }, { p::ampDecay, 0.4f },
            { p::ampSustain, 0 }, { p::reverbMix, 0.5f } } },
        { "Sequenced Acid", "ARP", { { p::arpMode, 1 }, { p::arpRate, 8 }, { p::arpGate, 0.55f },
            { p::cutoff, 300 }, { p::resonance, 0.85f }, { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.16f },
            { p::filtSustain, 0 }, { p::keyTrack, 0.8f }, { p::filterDrive, 10 }, { p::ampSustain, 0.6f },
            { p::delayMix, 0.2f }, { p::delayTime, 0.19f }, { p::arpOctaves, 2 } } },

        // ================= RHYTHM (generative / noise) =================
        { "Noise Ticker", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 4 },
            { p::arpRate, 10 }, { p::arpGate, 0.2f }, { p::cutoff, 4000 }, { p::resonance, 0.8f },
            { p::keyTrack, 1 }, { p::filtDecay, 0.07f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.6f },
            { p::ampDecay, 0.1f }, { p::ampSustain, 0 }, { p::delayMix, 0.25f }, { p::delayTime, 0.19f },
            { p::delayFeedback, 0.5f } } },
        { "Steam Engine", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.8f }, { p::subLevel, 0.3f },
            { p::arpMode, 1 }, { p::arpRate, 7 }, { p::arpGate, 0.35f }, { p::cutoff, 1500 },
            { p::resonance, 0.6f }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.1f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.15f }, { p::ampSustain, 0 }, { p::delayMix, 0.3f }, { p::character, 0.9f } } },
        { "Perc Circuit", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.1f }, { p::resonance, 1 },
            { p::keyTrack, 1 }, { p::arpMode, 4 }, { p::arpRate, 11 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.25f }, { p::cutoff, 880 }, { p::ampDecay, 0.1f }, { p::ampSustain, 0 },
            { p::delayMix, 0.3f }, { p::delayTime, 0.21f }, { p::delayFeedback, 0.55f }, { p::quality, 2 } } },
        { "Industrial Loom", "RHYTHM", { { p::osc1Wave, 2 }, { p::noiseLevel, 0.5f }, { p::arpMode, 2 },
            { p::arpRate, 9 }, { p::arpGate, 0.4f }, { p::cutoff, 900 }, { p::resonance, 0.7f },
            { p::filterDrive, 12 }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.1f }, { p::ampSustain, 0.3f },
            { p::delayMix, 0.28f }, { p::dnaWarmth, 0.9f }, { p::character, 0.8f } } },
        { "Rain on Tin", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 4 },
            { p::arpRate, 14 }, { p::arpOctaves, 2 }, { p::arpGate, 0.15f }, { p::cutoff, 6000 },
            { p::resonance, 0.85f }, { p::keyTrack, 1 }, { p::ampDecay, 0.05f }, { p::ampSustain, 0 },
            { p::filtDecay, 0.05f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.5f }, { p::reverbMix, 0.4f } } },
        { "Generative Dub", "RHYTHM", { { p::osc1Wave, 0 }, { p::subLevel, 0.6f }, { p::arpMode, 4 },
            { p::arpRate, 6 }, { p::arpOctaves, 2 }, { p::arpGate, 0.5f }, { p::cutoff, 700 },
            { p::resonance, 0.6f }, { p::delayMix, 0.45f }, { p::delayTime, 0.375f }, { p::delayFeedback, 0.7f },
            { p::driftAmount, 3 }, { p::character, 0.9f }, { p::ampSustain, 0.5f } } },
        { "Clockwork", "RHYTHM", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.2f }, { p::arpMode, 1 },
            { p::arpRate, 12 }, { p::arpGate, 0.25f }, { p::cutoff, 2500 }, { p::ampDecay, 0.08f },
            { p::ampSustain, 0 }, { p::filtDecay, 0.06f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.4f },
            { p::delayMix, 0.2f }, { p::delayTime, 0.167f }, { p::delayFeedback, 0.45f } } },
        { "Ghost Snare", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 3 },
            { p::arpRate, 8 }, { p::arpGate, 0.3f }, { p::cutoff, 2200 }, { p::resonance, 0.5f },
            { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.09f }, { p::filtSustain, 0 }, { p::ampDecay, 0.12f },
            { p::ampSustain, 0 }, { p::reverbMix, 0.3f }, { p::outputDrive, 8 } } },
        { "Tidal Pulse", "RHYTHM", { { p::noiseLevel, 0.3f }, { p::osc1Level, 0.8f }, { p::lfoShape, 3 },
            { p::lfoRate, 0.8f }, { p::lfoToCutoff, 0.5f }, { p::cutoff, 500 }, { p::ampAttack, 0.5f },
            { p::ampRelease, 1.5f }, { p::reverbMix, 0.45f }, { p::reverbSize, 0.85f }, { p::character, 0.9f } } },
        { "Morse Static", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.9f }, { p::arpMode, 4 },
            { p::arpRate, 16 }, { p::arpGate, 0.12f }, { p::cutoff, 3000 }, { p::resonance, 0.9f },
            { p::keyTrack, 1 }, { p::ampDecay, 0.05f }, { p::ampSustain, 0 }, { p::delayMix, 0.22f },
            { p::delayFeedback, 0.6f }, { p::dnaAge, 0.7f }, { p::character, 1 } } },

        // ================= DNA =================
        { "Ideal Mono Bass", "DNA", { { p::character, 0 }, { p::cutoff, 500 }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.3f } } },
        { "Analog DNA Mono Bass", "DNA", { { p::character, 0.8f }, { p::dnaCondition, 0.5f },
            { p::dnaWarmth, 0.6f }, { p::dnaAge, 0.4f }, { p::cutoff, 500 }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.3f } } },
        { "Warm Oscillator Lead", "DNA", { { p::character, 0.9f }, { p::dnaWarmth, 0.9f },
            { p::dnaCalibration, 0.6f }, { p::osc2Level, 0.85f }, { p::osc2Fine, 5 }, { p::cutoff, 2200 },
            { p::polyphony, 1 }, { p::glide, 0.04f } } },
        { "Aging Poly Chords", "DNA", { { p::character, 1 }, { p::dnaAge, 0.9f }, { p::dnaCondition, 0.8f },
            { p::dnaCalibration, 0.4f }, { p::osc2Level, 0.8f }, { p::cutoff, 2800 }, { p::ampAttack, 0.05f },
            { p::ampRelease, 0.6f }, { p::polyphony, 16 } } },
        { "Voice Round-Robin Keys", "DNA", { { p::character, 1 }, { p::dnaCalibration, 0.3f },
            { p::dnaCondition, 0.7f }, { p::cutoff, 3500 }, { p::ampDecay, 0.5f }, { p::ampSustain, 0.4f },
            { p::filterVel, 0.5f } } },
        { "Driven Ladder Bass", "DNA", { { p::character, 0.7f }, { p::dnaWarmth, 1 }, { p::mixerDrive, 5 },
            { p::filterDrive, 14 }, { p::cutoff, 420 }, { p::resonance, 0.5f }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filtDecay, 0.25f }, { p::filterEnvAmt, 0.5f } } },
        { "Soft Supply Pad", "DNA", { { p::character, 0.9f }, { p::dnaSupply, 0.05f }, { p::dnaWarmth, 0.5f },
            { p::osc2Level, 0.9f }, { p::osc2Fine, 7 }, { p::cutoff, 1800 }, { p::ampAttack, 0.4f },
            { p::ampRelease, 1 }, { p::polyphony, 16 }, { p::unisonCount, 2 } } },
        { "Worn Calibration Brass", "DNA", { { p::character, 1 }, { p::dnaCondition, 1 },
            { p::dnaCalibration, 0.1f }, { p::dnaAge, 0.7f }, { p::osc2Level, 0.85f }, { p::cutoff, 900 },
            { p::filterEnvAmt, 0.45f }, { p::filtSustain, 0.4f }, { p::ampAttack, 0.05f } } },
        { "Clean vs Saturated Seq", "DNA", { { p::character, 0.6f }, { p::dnaWarmth, 0.95f }, { p::arpMode, 1 },
            { p::arpRate, 8 }, { p::arpOctaves, 2 }, { p::arpGate, 0.45f }, { p::cutoff, 1000 },
            { p::resonance, 0.4f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0 },
            { p::ampSustain, 0.5f } } },
        { "Maximum DNA Demo", "DNA", { { p::character, 1 }, { p::dnaCondition, 1 }, { p::dnaCalibration, 0 },
            { p::dnaWarmth, 1 }, { p::dnaSupply, 0 }, { p::dnaAge, 1 }, { p::driftAmount, 6 },
            { p::warmup, 1 }, { p::osc2Level, 0.9f }, { p::cutoff, 2000 }, { p::polyphony, 16 } } },
    };
    return bank;
}

} // namespace sappsynth::presets
