#include "FactoryPresets.h"
#include "../parameters/ParameterIds.h"

namespace sappsynth::presets {
namespace p = sappsynth::param;

const std::vector<Preset>& all()
{
    static const std::vector<Preset> bank {
        { "Init", "INIT", { { p::master, -15.6f } } },

        // ================= BASS =================
        { "Acid Bass", "BASS", { { p::cutoff, 240 }, { p::resonance, 0.88f }, { p::filterEnvAmt, 0.75f },
            { p::filtDecay, 0.18f }, { p::filtSustain, 0 }, { p::keyTrack, 0.8f }, { p::filterDrive, 10 },
            { p::subLevel, 0.4f }, { p::ampDecay, 0.3f }, { p::ampRelease, 0.12f }, { p::polyphony, 1 },
            { p::filterVel, 0.6f }, { p::glide, 0.06f }, { p::delayMix, 0.22f }, { p::delayTime, 0.19f },
            { p::delayFeedback, 0.45f },
            { p::master, 2.4f } } },
        { "Model Growl", "BASS", { { p::osc2Level, 0.9f }, { p::osc2Fine, -8 }, { p::subLevel, 0.6f },
            { p::cutoff, 350 }, { p::resonance, 0.25f }, { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.25f },
            { p::filtSustain, 0.1f }, { p::keyTrack, 0.4f }, { p::mixerDrive, 3.5f }, { p::filterDrive, 8 },
            { p::character, 0.8f }, { p::polyphony, 1 }, { p::glide, 0.04f }, { p::ampRelease, 0.2f },
            { p::master, -0.8f } } },
        { "Taurus Rumble", "BASS", { { p::osc1Octave, -1 }, { p::subOctave, 1 }, { p::subLevel, 0.8f },
            { p::cutoff, 200 }, { p::mixerDrive, 3 }, { p::outputDrive, 6 }, { p::polyphony, 1 },
            { p::glide, 0.08f }, { p::ampRelease, 0.4f }, { p::character, 0.9f }, { p::filterEnvAmt, 0.3f },
            { p::filtDecay, 0.4f },
            { p::master, -9.5f } } },
        { "Velvet Bass", "BASS", { { p::osc1Wave, 3 }, { p::subLevel, 0.7f }, { p::cutoff, 380 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.3f }, { p::ampDecay, 0.4f }, { p::ampSustain, 0.6f },
            { p::dnaWarmth, 0.7f }, { p::character, 0.7f }, { p::polyphony, 1 },
            { p::master, -3.5f } } },
        { "Rubber Bass", "BASS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 12 },
            { p::osc2Fm, 0.28f }, { p::osc2Level, 0 }, { p::cutoff, 650 }, { p::filterEnvAmt, 0.5f },
            { p::filtDecay, 0.16f }, { p::filtSustain, 0 }, { p::ampDecay, 0.35f }, { p::filterVel, 0.6f },
            { p::polyphony, 1 }, { p::subLevel, 0.4f },
            { p::master, -3.1f } } },

        // ================= LEAD =================
        { "Fat Fifth Lead", "LEAD", { { p::osc2Semi, 7 }, { p::osc2Level, 0.9f }, { p::cutoff, 2500 },
            { p::resonance, 0.3f }, { p::polyphony, 1 }, { p::glide, 0.05f }, { p::character, 0.7f },
            { p::delayMix, 0.25f }, { p::unisonCount, 2 }, { p::unisonDetune, 8 }, { p::filterVel, 0.4f },
            { p::master, -0.8f } } },
        { "Lucky Lead", "LEAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 6 }, { p::unisonCount, 3 },
            { p::unisonDetune, 10 }, { p::cutoff, 1800 }, { p::filterEnvAmt, 0.4f }, { p::filterVel, 0.5f },
            { p::ampDecay, 0.5f }, { p::delayMix, 0.2f }, { p::character, 0.6f },
            { p::master, -10.5f } } },
        { "Hoover Rave", "LEAD", { { p::osc2Wave, 2 }, { p::osc2Pw, 0.4f }, { p::osc2Level, 0.9f },
            { p::unisonCount, 5 }, { p::unisonDetune, 35 }, { p::unisonSpread, 1 }, { p::cutoff, 3000 },
            { p::glide, 0.15f }, { p::chorusMix, 0.4f }, { p::ampAttack, 0.02f }, { p::character, 0.6f },
            { p::polyphony, 10 },
            { p::master, -12.3f } } },
        { "Whistle (Self-Osc)", "LEAD", { { p::osc1Level, 0 }, { p::noiseLevel, 0.06f }, { p::cutoff, 880 },
            { p::resonance, 1 }, { p::keyTrack, 1 }, { p::filterEnvAmt, 0 }, { p::ampAttack, 0.02f },
            { p::ampRelease, 0.5f }, { p::quality, 2 }, { p::reverbMix, 0.35f },
            { p::master, -3.9f } } },
        { "Silver Flute", "LEAD", { { p::osc1Wave, 0 }, { p::noiseLevel, 0.05f }, { p::cutoff, 2600 },
            { p::keyTrack, 1 }, { p::ampAttack, 0.06f }, { p::ampRelease, 0.3f }, { p::lfoRate, 5.5f },
            { p::lfoToPitch, 6 }, { p::polyphony, 1 }, { p::glide, 0.03f }, { p::reverbMix, 0.25f },
            { p::master, 0.4f } } },
        { "Solina Glide", "LEAD", { { p::osc1Wave, 1 }, { p::osc2Level, 0.85f }, { p::osc2Fine, 4 },
            { p::cutoff, 2000 }, { p::glide, 0.09f }, { p::polyphony, 1 }, { p::chorusMix, 0.5f },
            { p::character, 0.8f }, { p::ampRelease, 0.4f }, { p::delayMix, 0.2f },
            { p::master, 0.6f } } },

        // ================= KEYS =================
        { "Juno Chorus Keys", "KEYS", { { p::subLevel, 0.5f }, { p::cutoff, 4500 }, { p::ampAttack, 0.01f },
            { p::ampDecay, 0.4f }, { p::ampSustain, 0.6f }, { p::chorusMix, 0.6f }, { p::character, 0.6f },
            { p::filterVel, 0.4f }, { p::ampRelease, 0.3f },
            { p::master, -14.1f } } },
        { "Vintage Organ", "KEYS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.5f }, { p::subWave, 1 }, { p::subLevel, 0.8f }, { p::cutoff, 8000 },
            { p::ampAttack, 0.005f }, { p::ampSustain, 1 }, { p::ampRelease, 0.06f }, { p::chorusMix, 0.3f },
            { p::master, -16.9f } } },
        { "Punchy Pluck", "KEYS", { { p::osc2Wave, 2 }, { p::osc2Semi, -12 }, { p::osc2Level, 0.6f },
            { p::cutoff, 900 }, { p::resonance, 0.35f }, { p::filterEnvAmt, 0.8f }, { p::filtDecay, 0.12f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.35f }, { p::ampSustain, 0 }, { p::ampRelease, 0.25f },
            { p::keyTrack, 1 }, { p::filterVel, 0.6f }, { p::delayMix, 0.18f },
            { p::master, -12.2f } } },
        { "Warm Brass", "KEYS", { { p::osc2Level, 0.85f }, { p::osc2Fine, 4 }, { p::cutoff, 750 },
            { p::resonance, 0.15f }, { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.35f }, { p::filtSustain, 0.4f },
            { p::ampAttack, 0.04f }, { p::ampRelease, 0.3f }, { p::mixerDrive, 2.2f }, { p::character, 0.7f },
            { p::chorusMix, 0.2f }, { p::reverbMix, 0.18f },
            { p::master, -15.2f } } },
        { "Poly Comp Stab", "KEYS", { { p::osc2Wave, 2 }, { p::osc2Level, 0.8f }, { p::cutoff, 1600 },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.2f }, { p::filtSustain, 0.1f }, { p::ampDecay, 0.3f },
            { p::ampSustain, 0.2f }, { p::ampRelease, 0.2f }, { p::filterVel, 0.7f }, { p::chorusMix, 0.25f },
            { p::master, -16.9f } } },
        { "Church Organ", "KEYS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0.35f }, { p::subWave, 1 }, { p::subLevel, 0.9f }, { p::cutoff, 6000 },
            { p::ampAttack, 0.03f }, { p::ampSustain, 1 }, { p::ampRelease, 0.4f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.95f },
            { p::master, -20.5f } } },

        // ================= FM =================
        { "FM E-Piano", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.35f }, { p::cutoff, 8000 }, { p::ampDecay, 0.8f },
            { p::ampSustain, 0.3f }, { p::ampRelease, 0.4f }, { p::filterVel, 0.5f }, { p::reverbMix, 0.15f },
            { p::chorusMix, 0.25f },
            { p::master, -15.0f } } },
        { "FM Bells", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Fine, 30 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.5f }, { p::cutoff, 12000 },
            { p::ampAttack, 0.005f }, { p::ampDecay, 1.5f }, { p::ampSustain, 0 }, { p::ampRelease, 1.5f },
            { p::reverbMix, 0.4f }, { p::reverbSize, 0.7f },
            { p::master, -13.8f } } },
        { "Glass Clang", "FM", { { p::osc1Wave, 3 }, { p::osc2Wave, 2 }, { p::osc2Octave, 1 }, { p::osc2Semi, 6 },
            { p::osc2Level, 0.2f }, { p::osc2Fm, 0.7f }, { p::mixerDrive, 2 }, { p::cutoff, 9000 },
            { p::ampDecay, 0.6f }, { p::ampSustain, 0 }, { p::ampRelease, 0.5f }, { p::delayMix, 0.3f },
            { p::master, -17.2f } } },
        { "Metal Drone", "FM", { { p::osc2Octave, -1 }, { p::osc2Fine, 13 }, { p::osc2Level, 0.5f },
            { p::osc2Fm, 0.9f }, { p::resonance, 0.5f }, { p::cutoff, 1200 }, { p::character, 1 },
            { p::driftAmount, 4 }, { p::reverbMix, 0.5f }, { p::ampAttack, 0.5f }, { p::ampRelease, 2 },
            { p::quality, 2 },
            { p::master, -14.1f } } },
        { "Wurli Bite", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.42f }, { p::mixerDrive, 3 }, { p::dnaWarmth, 0.8f },
            { p::cutoff, 5000 }, { p::ampDecay, 0.6f }, { p::ampSustain, 0.4f }, { p::filterVel, 0.7f },
            { p::delayMix, 0.15f },
            { p::master, -19.8f } } },
        { "Sunken Bells", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 7 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.45f }, { p::cutoff, 4000 }, { p::ampAttack, 0.01f },
            { p::ampDecay, 2 }, { p::ampSustain, 0 }, { p::ampRelease, 2.5f }, { p::reverbMix, 0.65f },
            { p::reverbSize, 0.9f }, { p::delayMix, 0.3f }, { p::delayTime, 0.6f }, { p::delayFeedback, 0.55f },
            { p::master, -12.1f } } },

        // ================= PAD =================
        { "Drift Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 9 }, { p::subLevel, 0.5f },
            { p::cutoff, 1600 }, { p::ampAttack, 0.6f }, { p::ampRelease, 1.2f }, { p::filtAttack, 0.8f },
            { p::filterEnvAmt, 0.3f }, { p::character, 1 }, { p::driftAmount, 4 }, { p::warmup, 0.4f },
            { p::quality, 2 }, { p::reverbMix, 0.42f }, { p::reverbSize, 0.8f }, { p::delayMix, 0.18f },
            { p::master, -15.1f } } },
        { "Jupiter Sweep Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 5 }, { p::osc1Fine, -5 },
            { p::cutoff, 900 }, { p::lfoToCutoff, 0.35f }, { p::lfoRate, 0.15f }, { p::ampAttack, 0.8f },
            { p::ampRelease, 1.6f }, { p::chorusMix, 0.45f }, { p::reverbMix, 0.35f }, { p::character, 0.8f },
            { p::polyphony, 16 }, { p::unisonCount, 2 }, { p::unisonDetune, 9 },
            { p::master, -13.2f } } },
        { "PWM Strings", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.32f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.68f }, { p::osc2Fine, -6 }, { p::osc2Level, 0.8f }, { p::cutoff, 3800 },
            { p::ampAttack, 0.25f }, { p::ampRelease, 0.8f }, { p::lfoRate, 0.8f }, { p::lfoToPitch, 3 },
            { p::character, 0.8f }, { p::chorusMix, 0.5f }, { p::reverbMix, 0.3f },
            { p::master, -12.7f } } },
        { "Polysix Strings", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.65f }, { p::osc2Fine, -4 }, { p::osc2Level, 0.85f }, { p::cutoff, 3200 },
            { p::ampAttack, 0.35f }, { p::ampRelease, 1 }, { p::chorusMix, 0.55f }, { p::reverbMix, 0.25f },
            { p::lfoToPitch, 2 }, { p::lfoRate, 0.7f },
            { p::master, -14.9f } } },
        { "Super Saw Stack", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, -7 }, { p::unisonCount, 5 },
            { p::unisonDetune, 22 }, { p::unisonSpread, 0.9f }, { p::cutoff, 5200 }, { p::ampAttack, 0.02f },
            { p::ampRelease, 0.5f }, { p::chorusMix, 0.25f }, { p::reverbMix, 0.22f }, { p::polyphony, 16 },
            { p::master, -10.3f } } },
        { "Tape Flute", "PAD", { { p::osc1Wave, 0 }, { p::noiseLevel, 0.05f }, { p::cutoff, 3000 },
            { p::glide, 0.12f }, { p::character, 1 }, { p::driftAmount, 5 }, { p::warmup, 0.6f },
            { p::ampAttack, 0.08f }, { p::reverbMix, 0.3f }, { p::polyphony, 1 },
            { p::master, 0.1f } } },
        { "Glacier Pad", "PAD", { { p::osc2Level, 0.9f }, { p::osc2Fine, 6 }, { p::cutoff, 1200 },
            { p::ampAttack, 1.2f }, { p::ampRelease, 2.5f }, { p::reverbMix, 0.6f }, { p::reverbSize, 0.9f },
            { p::chorusMix, 0.3f }, { p::character, 0.8f }, { p::driftAmount, 3 }, { p::polyphony, 16 },
            { p::master, -14.5f } } },
        { "Analog Choir", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.45f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.55f }, { p::osc2Fine, 4 }, { p::osc1Fine, -4 }, { p::osc2Level, 0.9f },
            { p::cutoff, 2000 }, { p::chorusMix, 0.6f }, { p::ampAttack, 0.5f }, { p::ampRelease, 1.5f },
            { p::unisonCount, 2 }, { p::unisonDetune, 7 }, { p::reverbMix, 0.4f },
            { p::master, -9.4f } } },
        { "Dark Cathedral", "PAD", { { p::osc1Octave, -1 }, { p::subOctave, 1 }, { p::subLevel, 0.7f },
            { p::cutoff, 700 }, { p::resonance, 0.3f }, { p::ampAttack, 0.8f }, { p::ampRelease, 3 },
            { p::reverbMix, 0.7f }, { p::reverbSize, 1 }, { p::character, 0.8f }, { p::delayMix, 0.2f },
            { p::delayTime, 0.8f },
            { p::master, -21.2f } } },
        { "Warm Tape Pad", "PAD", { { p::osc1Wave, 3 }, { p::osc2Wave, 3 }, { p::osc2Fine, 8 },
            { p::osc2Level, 0.9f }, { p::dnaWarmth, 0.9f }, { p::dnaAge, 0.6f }, { p::character, 1 },
            { p::driftAmount, 5 }, { p::driftSpeed, 0.4f }, { p::cutoff, 1500 }, { p::chorusMix, 0.4f },
            { p::ampAttack, 0.6f }, { p::ampRelease, 2 },
            { p::master, -15.4f } } },
        { "Widescreen", "PAD", { { p::unisonCount, 4 }, { p::unisonDetune, 14 }, { p::unisonSpread, 1 },
            { p::osc2Level, 0.85f }, { p::cutoff, 2400 }, { p::ampAttack, 0.7f }, { p::ampRelease, 2 },
            { p::chorusMix, 0.35f }, { p::reverbMix, 0.4f }, { p::polyphony, 16 },
            { p::master, -9.2f } } },

        // ================= AMBIENT =================
        { "Aurora Swell", "AMBIENT", { { p::osc1Wave, 3 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.7f },
            { p::osc2Fine, 5 }, { p::lfoToCutoff, 0.3f }, { p::lfoRate, 0.07f }, { p::cutoff, 1100 },
            { p::ampAttack, 1.5f }, { p::ampRelease, 3 }, { p::delayMix, 0.3f }, { p::delayTime, 0.7f },
            { p::delayFeedback, 0.6f }, { p::reverbMix, 0.5f }, { p::reverbSize, 0.9f },
            { p::master, -13.5f } } },
        { "Shimmer Drift", "AMBIENT", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0.5f }, { p::osc2Fm, 0.15f }, { p::cutoff, 6000 }, { p::ampAttack, 1 },
            { p::ampRelease, 3 }, { p::reverbMix, 0.65f }, { p::reverbSize, 0.95f }, { p::driftAmount, 4 },
            { p::character, 0.9f },
            { p::master, -19.1f } } },
        { "Evening Haze", "AMBIENT", { { p::cutoff, 900 }, { p::lfoToCutoff, 0.15f }, { p::lfoRate, 0.1f },
            { p::ampAttack, 1 }, { p::ampRelease, 2.5f }, { p::delayMix, 0.35f }, { p::delayTime, 0.9f },
            { p::delayFeedback, 0.65f }, { p::reverbMix, 0.45f }, { p::character, 0.8f },
            { p::master, -11.4f } } },
        { "Slow Breath", "AMBIENT", { { p::noiseLevel, 0.15f }, { p::osc1Level, 0.6f }, { p::lfoShape, 1 },
            { p::lfoRate, 0.05f }, { p::lfoToCutoff, 0.4f }, { p::cutoff, 600 }, { p::ampAttack, 2 },
            { p::ampRelease, 3 }, { p::reverbMix, 0.5f }, { p::reverbSize, 0.9f },
            { p::master, -12.5f } } },
        { "Static Field", "AMBIENT", { { p::noiseLevel, 0.4f }, { p::osc1Level, 0.3f }, { p::cutoff, 3000 },
            { p::resonance, 0.55f }, { p::lfoShape, 2 }, { p::lfoRate, 0.12f }, { p::lfoToCutoff, 0.3f },
            { p::ampAttack, 1 }, { p::ampRelease, 2 }, { p::reverbMix, 0.6f }, { p::dnaAge, 0.8f },
            { p::character, 1 },
            { p::master, -7.1f } } },
        { "Hollow Reed", "AMBIENT", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.18f }, { p::cutoff, 1600 },
            { p::keyTrack, 1 }, { p::ampAttack, 0.3f }, { p::ampRelease, 1.5f }, { p::chorusMix, 0.25f },
            { p::reverbMix, 0.45f }, { p::reverbSize, 0.85f },
            { p::master, -15.5f } } },

        // ================= ARP =================
        { "Berlin School", "ARP", { { p::arpMode, 3 }, { p::arpRate, 6 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.55f }, { p::subLevel, 0.4f }, { p::cutoff, 1100 }, { p::resonance, 0.45f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0.2f }, { p::delayMix, 0.35f },
            { p::delayTime, 0.375f }, { p::delayFeedback, 0.55f }, { p::ampRelease, 0.15f },
            { p::master, -1.4f } } },
        { "Disco Octaves", "ARP", { { p::arpMode, 1 }, { p::arpRate, 9 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.4f }, { p::osc2Wave, 2 }, { p::osc2Semi, -12 }, { p::osc2Level, 0.6f },
            { p::cutoff, 1400 }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.12f }, { p::filtSustain, 0 },
            { p::ampSustain, 0.4f }, { p::ampRelease, 0.1f }, { p::delayMix, 0.2f },
            { p::master, -2.3f } } },
        { "Dream Cascade", "ARP", { { p::arpMode, 3 }, { p::arpRate, 7.2f }, { p::arpOctaves, 2 },
            { p::arpGate, 0.6f }, { p::osc2Wave, 3 }, { p::osc2Level, 0.7f }, { p::cutoff, 1500 },
            { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.2f }, { p::filtSustain, 0 }, { p::ampSustain, 0.5f },
            { p::delayMix, 0.32f }, { p::delayTime, 0.42f }, { p::delayFeedback, 0.5f }, { p::reverbMix, 0.35f },
            { p::master, -0.7f } } },
        { "Neon Nights", "ARP", { { p::arpMode, 1 }, { p::arpRate, 8.5f }, { p::arpGate, 0.5f },
            { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::cutoff, 1200 }, { p::resonance, 0.5f },
            { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.13f }, { p::filtSustain, 0.1f }, { p::ampSustain, 0.5f },
            { p::delayMix, 0.28f }, { p::delayTime, 0.33f }, { p::delayFeedback, 0.45f }, { p::chorusMix, 0.2f },
            { p::master, -0.7f } } },
        { "Crystal Run", "ARP", { { p::arpMode, 4 }, { p::arpRate, 12 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.35f }, { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.5f }, { p::cutoff, 6000 }, { p::keyTrack, 1 }, { p::ampDecay, 0.15f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.2f }, { p::reverbMix, 0.45f }, { p::delayMix, 0.3f },
            { p::master, -2.2f } } },
        { "Midnight Train", "ARP", { { p::arpMode, 2 }, { p::arpRate, 6 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.7f }, { p::subLevel, 0.6f }, { p::cutoff, 800 }, { p::resonance, 0.55f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.18f }, { p::ampSustain, 0.6f }, { p::delayMix, 0.4f },
            { p::delayTime, 0.375f }, { p::delayFeedback, 0.55f }, { p::character, 0.8f },
            { p::master, -1.0f } } },
        { "Pluck & Bloom", "ARP", { { p::arpMode, 1 }, { p::arpRate, 5 }, { p::arpGate, 0.5f },
            { p::cutoff, 1000 }, { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.4f }, { p::ampSustain, 0 }, { p::ampRelease, 0.5f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.8f }, { p::delayMix, 0.35f }, { p::delayTime, 0.6f },
            { p::master, -1.2f } } },
        { "Arcadia", "ARP", { { p::arpMode, 3 }, { p::arpRate, 9 }, { p::arpOctaves, 2 }, { p::arpGate, 0.45f },
            { p::osc1Wave, 2 }, { p::osc2Level, 0.8f }, { p::osc2Fine, 5 }, { p::cutoff, 1800 },
            { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.14f }, { p::ampSustain, 0.4f }, { p::chorusMix, 0.3f },
            { p::delayMix, 0.25f },
            { p::master, -1.7f } } },
        { "Harp Machine", "ARP", { { p::arpMode, 1 }, { p::arpRate, 10 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.3f }, { p::osc1Wave, 3 }, { p::cutoff, 4000 }, { p::keyTrack, 1 },
            { p::ampDecay, 0.3f }, { p::ampSustain, 0 }, { p::ampRelease, 0.6f }, { p::reverbMix, 0.55f },
            { p::reverbSize, 0.85f },
            { p::master, -7.8f } } },
        { "Berlin Sunrise", "ARP", { { p::arpMode, 3 }, { p::arpRate, 5.5f }, { p::arpOctaves, 3 },
            { p::arpGate, 0.6f }, { p::osc2Level, 0.85f }, { p::osc2Fine, 7 }, { p::cutoff, 1300 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.2f }, { p::ampSustain, 0.5f }, { p::delayMix, 0.45f },
            { p::delayTime, 0.5f }, { p::delayFeedback, 0.6f }, { p::driftAmount, 2 }, { p::character, 0.7f },
            { p::master, -1.2f } } },
        { "Gamelan Steps", "ARP", { { p::arpMode, 4 }, { p::arpRate, 9 }, { p::arpOctaves, 2 },
            { p::arpGate, 0.4f }, { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 }, { p::osc2Semi, 5 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.5f }, { p::cutoff, 8000 }, { p::ampDecay, 0.4f },
            { p::ampSustain, 0 }, { p::reverbMix, 0.5f },
            { p::master, -6.2f } } },
        { "Sequenced Acid", "ARP", { { p::arpMode, 1 }, { p::arpRate, 8 }, { p::arpGate, 0.55f },
            { p::cutoff, 300 }, { p::resonance, 0.85f }, { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.16f },
            { p::filtSustain, 0 }, { p::keyTrack, 0.8f }, { p::filterDrive, 10 }, { p::ampSustain, 0.6f },
            { p::delayMix, 0.2f }, { p::delayTime, 0.19f }, { p::arpOctaves, 2 },
            { p::master, 0.8f } } },

        // ================= RHYTHM (generative / noise) =================
        { "Noise Ticker", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 4 },
            { p::arpRate, 10 }, { p::arpGate, 0.2f }, { p::cutoff, 4000 }, { p::resonance, 0.8f },
            { p::keyTrack, 1 }, { p::filtDecay, 0.07f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.6f },
            { p::ampDecay, 0.1f }, { p::ampSustain, 0 }, { p::delayMix, 0.25f }, { p::delayTime, 0.19f },
            { p::delayFeedback, 0.5f },
            { p::master, -0.6f } } },
        { "Steam Engine", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.8f }, { p::subLevel, 0.3f },
            { p::arpMode, 1 }, { p::arpRate, 7 }, { p::arpGate, 0.35f }, { p::cutoff, 1500 },
            { p::resonance, 0.6f }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.1f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.15f }, { p::ampSustain, 0 }, { p::delayMix, 0.3f }, { p::character, 0.9f },
            { p::master, 0.7f } } },
        { "Perc Circuit", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.1f }, { p::resonance, 1 },
            { p::keyTrack, 1 }, { p::arpMode, 4 }, { p::arpRate, 11 }, { p::arpOctaves, 3 },
            { p::arpGate, 0.25f }, { p::cutoff, 880 }, { p::ampDecay, 0.1f }, { p::ampSustain, 0 },
            { p::delayMix, 0.3f }, { p::delayTime, 0.21f }, { p::delayFeedback, 0.55f }, { p::quality, 2 },
            { p::master, 6.0f } } },
        { "Industrial Loom", "RHYTHM", { { p::osc1Wave, 2 }, { p::noiseLevel, 0.5f }, { p::arpMode, 2 },
            { p::arpRate, 9 }, { p::arpGate, 0.4f }, { p::cutoff, 900 }, { p::resonance, 0.7f },
            { p::filterDrive, 12 }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.1f }, { p::ampSustain, 0.3f },
            { p::delayMix, 0.28f }, { p::dnaWarmth, 0.9f }, { p::character, 0.8f },
            { p::master, 2.8f } } },
        { "Rain on Tin", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 4 },
            { p::arpRate, 14 }, { p::arpOctaves, 2 }, { p::arpGate, 0.15f }, { p::cutoff, 6000 },
            { p::resonance, 0.85f }, { p::keyTrack, 1 }, { p::ampDecay, 0.05f }, { p::ampSustain, 0 },
            { p::filtDecay, 0.05f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.5f }, { p::reverbMix, 0.4f },
            { p::master, 0.6f } } },
        { "Generative Dub", "RHYTHM", { { p::osc1Wave, 0 }, { p::subLevel, 0.6f }, { p::arpMode, 4 },
            { p::arpRate, 6 }, { p::arpOctaves, 2 }, { p::arpGate, 0.5f }, { p::cutoff, 700 },
            { p::resonance, 0.6f }, { p::delayMix, 0.45f }, { p::delayTime, 0.375f }, { p::delayFeedback, 0.7f },
            { p::driftAmount, 3 }, { p::character, 0.9f }, { p::ampSustain, 0.5f },
            { p::master, 0.1f } } },
        { "Clockwork", "RHYTHM", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.2f }, { p::arpMode, 1 },
            { p::arpRate, 12 }, { p::arpGate, 0.25f }, { p::cutoff, 2500 }, { p::ampDecay, 0.08f },
            { p::ampSustain, 0 }, { p::filtDecay, 0.06f }, { p::filtSustain, 0 }, { p::filterEnvAmt, 0.4f },
            { p::delayMix, 0.2f }, { p::delayTime, 0.167f }, { p::delayFeedback, 0.45f },
            { p::master, -4.4f } } },
        { "Ghost Snare", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 1 }, { p::arpMode, 3 },
            { p::arpRate, 8 }, { p::arpGate, 0.3f }, { p::cutoff, 2200 }, { p::resonance, 0.5f },
            { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.09f }, { p::filtSustain, 0 }, { p::ampDecay, 0.12f },
            { p::ampSustain, 0 }, { p::reverbMix, 0.3f }, { p::outputDrive, 8 },
            { p::master, -7.8f } } },
        { "Tidal Pulse", "RHYTHM", { { p::noiseLevel, 0.3f }, { p::osc1Level, 0.8f }, { p::lfoShape, 3 },
            { p::lfoRate, 0.8f }, { p::lfoToCutoff, 0.5f }, { p::cutoff, 500 }, { p::ampAttack, 0.5f },
            { p::ampRelease, 1.5f }, { p::reverbMix, 0.45f }, { p::reverbSize, 0.85f }, { p::character, 0.9f },
            { p::master, -11.9f } } },
        { "Morse Static", "RHYTHM", { { p::osc1Level, 0 }, { p::noiseLevel, 0.9f }, { p::arpMode, 4 },
            { p::arpRate, 16 }, { p::arpGate, 0.12f }, { p::cutoff, 3000 }, { p::resonance, 0.9f },
            { p::keyTrack, 1 }, { p::ampDecay, 0.05f }, { p::ampSustain, 0 }, { p::delayMix, 0.22f },
            { p::delayFeedback, 0.6f }, { p::dnaAge, 0.7f }, { p::character, 1 },
            { p::master, -0.1f } } },

        // ================= DNA =================
        { "Ideal Mono Bass", "DNA", { { p::character, 0 }, { p::cutoff, 500 }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.3f },
            { p::master, -3.5f } } },
        { "Analog DNA Mono Bass", "DNA", { { p::character, 0.8f }, { p::dnaCondition, 0.5f },
            { p::dnaWarmth, 0.6f }, { p::dnaAge, 0.4f }, { p::cutoff, 500 }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.3f },
            { p::master, -3.1f } } },
        { "Warm Oscillator Lead", "DNA", { { p::character, 0.9f }, { p::dnaWarmth, 0.9f },
            { p::dnaCalibration, 0.6f }, { p::osc2Level, 0.85f }, { p::osc2Fine, 5 }, { p::cutoff, 2200 },
            { p::polyphony, 1 }, { p::glide, 0.04f },
            { p::master, -3.3f } } },
        { "Aging Poly Chords", "DNA", { { p::character, 1 }, { p::dnaAge, 0.9f }, { p::dnaCondition, 0.8f },
            { p::dnaCalibration, 0.4f }, { p::osc2Level, 0.8f }, { p::cutoff, 2800 }, { p::ampAttack, 0.05f },
            { p::ampRelease, 0.6f }, { p::polyphony, 16 },
            { p::master, -16.2f } } },
        { "Voice Round-Robin Keys", "DNA", { { p::character, 1 }, { p::dnaCalibration, 0.3f },
            { p::dnaCondition, 0.7f }, { p::cutoff, 3500 }, { p::ampDecay, 0.5f }, { p::ampSustain, 0.4f },
            { p::filterVel, 0.5f },
            { p::master, -15.3f } } },
        { "Driven Ladder Bass", "DNA", { { p::character, 0.7f }, { p::dnaWarmth, 1 }, { p::mixerDrive, 5 },
            { p::filterDrive, 14 }, { p::cutoff, 420 }, { p::resonance, 0.5f }, { p::subLevel, 0.5f },
            { p::polyphony, 1 }, { p::filtDecay, 0.25f }, { p::filterEnvAmt, 0.5f },
            { p::master, 2.5f } } },
        { "Soft Supply Pad", "DNA", { { p::character, 0.9f }, { p::dnaSupply, 0.05f }, { p::dnaWarmth, 0.5f },
            { p::osc2Level, 0.9f }, { p::osc2Fine, 7 }, { p::cutoff, 1800 }, { p::ampAttack, 0.4f },
            { p::ampRelease, 1 }, { p::polyphony, 16 }, { p::unisonCount, 2 },
            { p::master, -19.3f } } },
        { "Worn Calibration Brass", "DNA", { { p::character, 1 }, { p::dnaCondition, 1 },
            { p::dnaCalibration, 0.1f }, { p::dnaAge, 0.7f }, { p::osc2Level, 0.85f }, { p::cutoff, 900 },
            { p::filterEnvAmt, 0.45f }, { p::filtSustain, 0.4f }, { p::ampAttack, 0.05f },
            { p::master, -15.8f } } },
        { "Clean vs Saturated Seq", "DNA", { { p::character, 0.6f }, { p::dnaWarmth, 0.95f }, { p::arpMode, 1 },
            { p::arpRate, 8 }, { p::arpOctaves, 2 }, { p::arpGate, 0.45f }, { p::cutoff, 1000 },
            { p::resonance, 0.4f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0 },
            { p::ampSustain, 0.5f },
            { p::master, -4.1f } } },
        { "Maximum DNA Demo", "DNA", { { p::character, 1 }, { p::dnaCondition, 1 }, { p::dnaCalibration, 0 },
            { p::dnaWarmth, 1 }, { p::dnaSupply, 0 }, { p::dnaAge, 1 }, { p::driftAmount, 6 },
            { p::warmup, 1 }, { p::osc2Level, 0.9f }, { p::cutoff, 2000 }, { p::polyphony, 16 },
            { p::master, -18.7f } } },

        // ================= LADDER (classic ladder-filter mono) =================
        { "Ladder Lead", "LADDER", { { p::osc2Level, 0.85f }, { p::osc2Fine, -7 }, { p::cutoff, 1700 },
            { p::resonance, 0.38f }, { p::filterEnvAmt, 0.42f }, { p::filtDecay, 0.35f }, { p::filtSustain, 0.35f },
            { p::filterDrive, 6 }, { p::mixerDrive, 2.4f }, { p::polyphony, 1 }, { p::glide, 0.035f },
            { p::ampRelease, 0.25f }, { p::character, 0.75f }, { p::driftAmount, 2.5f },
            { p::master, -1.7f } } },
        { "Model D Brass", "LADDER", { { p::osc2Level, 0.9f }, { p::osc2Fine, 9 }, { p::subLevel, 0.35f },
            { p::cutoff, 900 }, { p::resonance, 0.22f }, { p::filterEnvAmt, 0.55f }, { p::filtAttack, 0.05f },
            { p::filtDecay, 0.45f }, { p::filtSustain, 0.45f }, { p::ampAttack, 0.03f }, { p::ampRelease, 0.3f },
            { p::mixerDrive, 2.8f }, { p::character, 0.7f }, { p::polyphony, 4 },
            { p::master, -16.0f } } },
        { "Fat Mono Bass", "LADDER", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::osc2Level, 0.7f },
            { p::osc2Fine, -11 }, { p::subLevel, 0.75f }, { p::cutoff, 320 }, { p::resonance, 0.2f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.22f }, { p::filtSustain, 0.05f }, { p::filterDrive, 9 },
            { p::polyphony, 1 }, { p::glide, 0.02f }, { p::ampRelease, 0.15f }, { p::character, 0.8f },
            { p::master, -0.1f } } },
        { "Emerson Solo", "LADDER", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.28f }, { p::osc2Wave, 1 },
            { p::osc2Level, 0.8f }, { p::osc2Semi, 7 }, { p::cutoff, 2400 }, { p::resonance, 0.55f },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.3f }, { p::keyTrack, 0.7f }, { p::polyphony, 1 },
            { p::glide, 0.06f }, { p::mixerDrive, 3.2f }, { p::delayMix, 0.18f }, { p::character, 0.85f },
            { p::master, -1.8f } } },
        { "Ladder Sub Bass", "LADDER", { { p::osc1Wave, 3 }, { p::subLevel, 0.9f }, { p::subOctave, 1 },
            { p::cutoff, 180 }, { p::resonance, 0.1f }, { p::filterEnvAmt, 0.2f }, { p::filtDecay, 0.3f },
            { p::polyphony, 1 }, { p::glide, 0.05f }, { p::ampRelease, 0.35f }, { p::outputDrive, 4 },
            { p::master, -7.4f } } },
        { "Portamento Lead", "LADDER", { { p::osc2Level, 0.75f }, { p::osc2Semi, -12 }, { p::cutoff, 2000 },
            { p::resonance, 0.3f }, { p::filterEnvAmt, 0.3f }, { p::polyphony, 1 }, { p::glide, 0.16f },
            { p::ampRelease, 0.3f }, { p::lfoRate, 5 }, { p::lfoToPitch, 8 }, { p::delayMix, 0.22f },
            { p::delayFeedback, 0.35f }, { p::character, 0.7f },
            { p::master, -0.7f } } },
        { "Filter Growl Bass", "LADDER", { { p::osc1Wave, 1 }, { p::osc2Level, 0.85f }, { p::osc2Fine, 14 },
            { p::cutoff, 260 }, { p::resonance, 0.62f }, { p::filterEnvAmt, 0.72f }, { p::filtDecay, 0.28f },
            { p::filtSustain, 0.1f }, { p::filterDrive, 12 }, { p::mixerDrive, 3.5f }, { p::polyphony, 1 },
            { p::filterVel, 0.7f }, { p::character, 0.9f },
            { p::master, 1.4f } } },
        { "Woody Lead", "LADDER", { { p::osc1Wave, 3 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.2f },
            { p::osc2Level, 0.45f }, { p::cutoff, 1400 }, { p::resonance, 0.25f }, { p::keyTrack, 0.8f },
            { p::ampAttack, 0.02f }, { p::ampRelease, 0.28f }, { p::polyphony, 1 }, { p::glide, 0.03f },
            { p::reverbMix, 0.2f },
            { p::master, 0.6f } } },
        { "Resonant Blip", "LADDER", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.15f }, { p::cutoff, 700 },
            { p::resonance, 0.85f }, { p::filterEnvAmt, 0.9f }, { p::filtDecay, 0.09f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.14f }, { p::ampSustain, 0 }, { p::ampRelease, 0.12f }, { p::keyTrack, 0.9f },
            { p::delayMix, 0.25f }, { p::delayTime, 0.18f },
            { p::master, -7.7f } } },
        { "Ladder Brass Stab", "LADDER", { { p::osc2Level, 0.9f }, { p::osc2Fine, 12 }, { p::cutoff, 1100 },
            { p::resonance, 0.3f }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.18f }, { p::filtSustain, 0.15f },
            { p::ampDecay, 0.25f }, { p::ampSustain, 0.2f }, { p::ampRelease, 0.2f }, { p::filterVel, 0.75f },
            { p::mixerDrive, 3 }, { p::polyphony, 6 },
            { p::master, -16.4f } } },
        { "Bass Pedal", "LADDER", { { p::osc1Octave, -1 }, { p::osc1Wave, 1 }, { p::subLevel, 0.85f },
            { p::cutoff, 220 }, { p::filterEnvAmt, 0.25f }, { p::ampAttack, 0.02f }, { p::ampRelease, 0.6f },
            { p::polyphony, 2 }, { p::outputDrive, 3 }, { p::dnaWarmth, 0.8f },
            { p::master, -12.5f } } },
        { "Screaming Lead", "LADDER", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.12f }, { p::osc2Level, 0.8f },
            { p::osc2Fine, -18 }, { p::cutoff, 3200 }, { p::resonance, 0.7f }, { p::filterDrive, 14 },
            { p::mixerDrive, 4.5f }, { p::polyphony, 1 }, { p::glide, 0.04f }, { p::lfoRate, 6.5f },
            { p::lfoToPitch, 12 }, { p::delayMix, 0.3f }, { p::reverbMix, 0.2f },
            { p::master, 3.8f } } },

        // ================= POLY (vintage polysynth) =================
        { "Jupiter Strings", "POLY", { { p::osc2Level, 0.9f }, { p::osc2Fine, 8 }, { p::osc2Octave, 1 },
            { p::cutoff, 3800 }, { p::resonance, 0.12f }, { p::ampAttack, 0.35f }, { p::ampDecay, 1.2f },
            { p::ampSustain, 0.85f }, { p::ampRelease, 1.1f }, { p::chorusMix, 0.65f }, { p::chorusRate, 0.35f },
            { p::reverbMix, 0.3f }, { p::polyphony, 12 }, { p::character, 0.6f }, { p::driftAmount, 3 },
            { p::master, -12.6f } } },
        { "Jupiter Brass", "POLY", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.4f },
            { p::osc2Level, 0.85f }, { p::osc2Fine, 6 }, { p::cutoff, 1200 }, { p::filterEnvAmt, 0.5f },
            { p::filtAttack, 0.06f }, { p::filtDecay, 0.5f }, { p::filtSustain, 0.5f }, { p::ampAttack, 0.05f },
            { p::ampRelease, 0.35f }, { p::chorusMix, 0.3f }, { p::mixerDrive, 2.2f }, { p::polyphony, 8 },
            { p::master, -19.3f } } },
        { "Prophet Poly", "POLY", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.35f },
            { p::osc2Level, 0.7f }, { p::osc2Fine, -6 }, { p::cutoff, 2200 }, { p::resonance, 0.2f },
            { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.6f }, { p::filtSustain, 0.4f }, { p::ampDecay, 0.8f },
            { p::ampSustain, 0.7f }, { p::ampRelease, 0.5f }, { p::polyphony, 8 }, { p::character, 0.65f },
            { p::master, -19.0f } } },
        { "Juno Pad Classic", "POLY", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.5f }, { p::subLevel, 0.55f },
            { p::cutoff, 2600 }, { p::ampAttack, 0.5f }, { p::ampSustain, 0.9f }, { p::ampRelease, 1.4f },
            { p::chorusMix, 0.75f }, { p::chorusRate, 0.5f }, { p::lfoRate, 0.35f }, { p::lfoToCutoff, 0.12f },
            { p::polyphony, 10 }, { p::reverbMix, 0.28f },
            { p::master, -14.7f } } },
        { "PWM Ensemble", "POLY", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.45f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.55f }, { p::osc2Level, 0.9f }, { p::osc2Fine, 11 }, { p::cutoff, 3000 },
            { p::lfoRate, 0.28f }, { p::lfoToCutoff, 0.18f }, { p::ampAttack, 0.4f }, { p::ampSustain, 0.85f },
            { p::ampRelease, 1.2f }, { p::chorusMix, 0.5f }, { p::polyphony, 12 },
            { p::master, -15.9f } } },
        { "Poly Stab", "POLY", { { p::osc2Level, 0.9f }, { p::osc2Semi, 12 }, { p::cutoff, 1800 },
            { p::resonance, 0.3f }, { p::filterEnvAmt, 0.65f }, { p::filtDecay, 0.14f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.22f }, { p::ampSustain, 0.1f }, { p::ampRelease, 0.18f }, { p::filterVel, 0.8f },
            { p::polyphony, 8 }, { p::delayMix, 0.15f },
            { p::master, -15.2f } } },
        { "Poly Voices", "POLY", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.6f }, { p::osc2Wave, 3 },
            { p::osc2Level, 0.7f }, { p::osc2Fine, -9 }, { p::noiseLevel, 0.04f }, { p::cutoff, 1900 },
            { p::ampAttack, 0.6f }, { p::ampSustain, 0.9f }, { p::ampRelease, 1.6f }, { p::chorusMix, 0.55f },
            { p::reverbMix, 0.45f }, { p::reverbSize, 0.8f }, { p::polyphony, 10 },
            { p::master, -17.2f } } },
        { "Vintage Poly Keys", "POLY", { { p::osc2Level, 0.6f }, { p::osc2Fine, 7 }, { p::cutoff, 3200 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.5f }, { p::filtSustain, 0.25f }, { p::ampDecay, 0.7f },
            { p::ampSustain, 0.45f }, { p::ampRelease, 0.4f }, { p::filterVel, 0.55f }, { p::chorusMix, 0.35f },
            { p::polyphony, 8 }, { p::dnaWarmth, 0.6f },
            { p::master, -13.8f } } },
        { "String Machine", "POLY", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.95f },
            { p::osc2Fine, 13 }, { p::osc2Octave, 1 }, { p::cutoff, 4200 }, { p::ampAttack, 0.25f },
            { p::ampSustain, 0.95f }, { p::ampRelease, 0.9f }, { p::chorusMix, 0.85f }, { p::chorusRate, 0.8f },
            { p::polyphony, 12 }, { p::dnaAge, 0.5f },
            { p::master, -17.1f } } },
        { "Brass Section", "POLY", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.9f },
            { p::osc2Fine, -10 }, { p::cutoff, 1000 }, { p::filterEnvAmt, 0.6f }, { p::filtAttack, 0.08f },
            { p::filtDecay, 0.4f }, { p::filtSustain, 0.55f }, { p::ampAttack, 0.06f }, { p::ampRelease, 0.4f },
            { p::mixerDrive, 2.5f }, { p::reverbMix, 0.22f }, { p::polyphony, 8 },
            { p::master, -17.8f } } },
        { "Soft Poly Pad", "POLY", { { p::osc1Wave, 3 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.5f },
            { p::osc2Fine, 5 }, { p::cutoff, 1500 }, { p::ampAttack, 0.9f }, { p::ampSustain, 0.9f },
            { p::ampRelease, 2 }, { p::chorusMix, 0.4f }, { p::reverbMix, 0.4f }, { p::reverbSize, 0.75f },
            { p::polyphony, 12 },
            { p::master, -12.1f } } },
        { "Detuned Organ", "POLY", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.6f }, { p::osc2Fine, 12 }, { p::subWave, 1 }, { p::subLevel, 0.7f },
            { p::cutoff, 7000 }, { p::ampAttack, 0.006f }, { p::ampSustain, 1 }, { p::ampRelease, 0.08f },
            { p::chorusMix, 0.45f }, { p::polyphony, 10 },
            { p::master, -17.5f } } },

        // ================= FM DIGITAL =================
        { "DX Tine EP", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.42f }, { p::cutoff, 9000 }, { p::ampDecay, 1.6f },
            { p::ampSustain, 0.25f }, { p::ampRelease, 0.5f }, { p::filterVel, 0.5f }, { p::chorusMix, 0.25f },
            { p::polyphony, 12 }, { p::reverbMix, 0.2f },
            { p::master, -13.6f } } },
        { "FM Bell Keys", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 7 },
            { p::osc2Octave, 2 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.55f }, { p::cutoff, 12000 },
            { p::ampDecay, 2.2f }, { p::ampSustain, 0.1f }, { p::ampRelease, 1.2f }, { p::reverbMix, 0.35f },
            { p::polyphony, 10 },
            { p::master, -15.4f } } },
        { "Glass Marimba", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.3f }, { p::cutoff, 8000 }, { p::ampDecay, 0.7f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.4f }, { p::filterVel, 0.6f }, { p::reverbMix, 0.3f },
            { p::polyphony, 10 },
            { p::master, -15.1f } } },
        { "FM Bass Slap", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Semi, 5 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.5f }, { p::subLevel, 0.5f },
            { p::cutoff, 2200 }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.1f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.4f }, { p::ampSustain, 0.15f }, { p::ampRelease, 0.15f }, { p::polyphony, 2 },
            { p::filterVel, 0.7f },
            { p::master, -9.2f } } },
        { "Tubular Bell", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 11 },
            { p::osc2Octave, 1 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.62f }, { p::cutoff, 14000 },
            { p::ampAttack, 0.004f }, { p::ampDecay, 3.5f }, { p::ampSustain, 0 }, { p::ampRelease, 2.5f },
            { p::reverbMix, 0.5f }, { p::reverbSize, 0.9f }, { p::polyphony, 8 },
            { p::master, -16.8f } } },
        { "FM Brass", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Level, 0 },
            { p::osc2Fm, 0.34f }, { p::cutoff, 3000 }, { p::filterEnvAmt, 0.45f }, { p::filtAttack, 0.07f },
            { p::filtDecay, 0.5f }, { p::filtSustain, 0.5f }, { p::ampAttack, 0.05f }, { p::ampRelease, 0.3f },
            { p::mixerDrive, 2 }, { p::polyphony, 8 },
            { p::master, -18.8f } } },
        { "Metal Pad", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Semi, 6 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.28f }, { p::cutoff, 4000 }, { p::ampAttack, 1.2f },
            { p::ampSustain, 0.8f }, { p::ampRelease, 2.2f }, { p::chorusMix, 0.4f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.85f }, { p::polyphony, 10 },
            { p::master, -14.6f } } },
        { "Digital Harp", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.22f }, { p::cutoff, 9000 }, { p::ampDecay, 1.1f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.8f }, { p::filterVel, 0.5f }, { p::delayMix, 0.25f },
            { p::delayTime, 0.28f }, { p::reverbMix, 0.35f }, { p::polyphony, 12 },
            { p::master, -12.0f } } },
        { "FM Clav", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Semi, 7 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.48f }, { p::cutoff, 4500 },
            { p::resonance, 0.25f }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.12f }, { p::ampDecay, 0.3f },
            { p::ampSustain, 0.05f }, { p::ampRelease, 0.12f }, { p::filterVel, 0.8f }, { p::polyphony, 8 },
            { p::master, -16.4f } } },
        { "Bell Pad", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.2f }, { p::cutoff, 6000 }, { p::ampAttack, 0.8f },
            { p::ampSustain, 0.7f }, { p::ampRelease, 2.5f }, { p::chorusMix, 0.35f }, { p::reverbMix, 0.55f },
            { p::reverbSize, 0.9f }, { p::polyphony, 10 }, { p::lfoRate, 0.2f }, { p::lfoToCutoff, 0.15f },
            { p::master, -13.0f } } },
        { "Wood Bass FM", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.26f }, { p::subLevel, 0.6f }, { p::cutoff, 900 },
            { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.2f }, { p::ampDecay, 0.6f }, { p::ampSustain, 0.2f },
            { p::ampRelease, 0.25f }, { p::polyphony, 1 }, { p::glide, 0.03f },
            { p::master, -3.4f } } },
        { "FM Whistle", "FM", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.14f }, { p::cutoff, 6000 }, { p::ampAttack, 0.08f },
            { p::ampRelease, 0.4f }, { p::lfoRate, 5.2f }, { p::lfoToPitch, 7 }, { p::polyphony, 1 },
            { p::glide, 0.04f }, { p::reverbMix, 0.3f },
            { p::master, 0.9f } } },

        // ================= TRANCE =================
        { "Supersaw Lead", "TRANCE", { { p::osc2Level, 0.95f }, { p::osc2Fine, 14 }, { p::unisonCount, 5 },
            { p::unisonDetune, 26 }, { p::unisonSpread, 0.9f }, { p::cutoff, 5000 }, { p::filterEnvAmt, 0.3f },
            { p::filtDecay, 0.4f }, { p::ampAttack, 0.01f }, { p::ampRelease, 0.35f }, { p::delayMix, 0.3f },
            { p::delayTime, 0.375f }, { p::delayFeedback, 0.4f }, { p::reverbMix, 0.28f }, { p::polyphony, 10 },
            { p::master, -7.1f } } },
        { "Trance Pluck", "TRANCE", { { p::osc2Level, 0.8f }, { p::osc2Fine, 10 }, { p::unisonCount, 3 },
            { p::unisonDetune, 18 }, { p::cutoff, 2600 }, { p::resonance, 0.3f }, { p::filterEnvAmt, 0.7f },
            { p::filtDecay, 0.1f }, { p::filtSustain, 0 }, { p::ampDecay, 0.22f }, { p::ampSustain, 0 },
            { p::ampRelease, 0.2f }, { p::delayMix, 0.35f }, { p::delayTime, 0.28f }, { p::delayFeedback, 0.45f },
            { p::reverbMix, 0.3f },
            { p::master, -1.3f } } },
        { "Gated Trance Pad", "TRANCE", { { p::osc2Level, 0.9f }, { p::osc2Fine, 12 }, { p::unisonCount, 4 },
            { p::unisonDetune, 20 }, { p::cutoff, 3400 }, { p::lfoRate, 8 }, { p::lfoShape, 3 },
            { p::lfoToCutoff, 0.75f }, { p::ampAttack, 0.05f }, { p::ampSustain, 0.9f }, { p::ampRelease, 0.6f },
            { p::reverbMix, 0.4f }, { p::polyphony, 10 },
            { p::master, -12.7f } } },
        { "Rolling Bass", "TRANCE", { { p::osc1Wave, 1 }, { p::subLevel, 0.7f }, { p::cutoff, 420 },
            { p::resonance, 0.25f }, { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.14f }, { p::filtSustain, 0 },
            { p::ampAttack, 0.004f }, { p::ampDecay, 0.18f }, { p::ampSustain, 0 }, { p::ampRelease, 0.1f },
            { p::polyphony, 1 }, { p::outputDrive, 3 },
            { p::master, -6.1f } } },
        { "Uplifting Arp", "TRANCE", { { p::osc2Level, 0.85f }, { p::osc2Fine, 9 }, { p::arpMode, 1 },
            { p::arpRate, 12 }, { p::arpOctaves, 2 }, { p::arpGate, 0.4f }, { p::cutoff, 3000 },
            { p::resonance, 0.28f }, { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.12f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.2f }, { p::ampSustain, 0 }, { p::delayMix, 0.32f }, { p::delayTime, 0.25f },
            { p::reverbMix, 0.3f },
            { p::master, -0.5f } } },
        { "Hoover Blast", "TRANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.3f }, { p::osc2Wave, 1 },
            { p::osc2Level, 0.9f }, { p::osc2Fine, -22 }, { p::unisonCount, 4 }, { p::unisonDetune, 32 },
            { p::cutoff, 2400 }, { p::resonance, 0.35f }, { p::glide, 0.12f }, { p::lfoRate, 0.8f },
            { p::lfoToPitch, 25 }, { p::mixerDrive, 3 }, { p::chorusMix, 0.35f }, { p::polyphony, 6 },
            { p::master, -10.9f } } },
        { "Anthem Chords", "TRANCE", { { p::osc2Level, 0.9f }, { p::osc2Fine, 16 }, { p::unisonCount, 3 },
            { p::unisonDetune, 22 }, { p::cutoff, 3600 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.5f },
            { p::filtSustain, 0.4f }, { p::ampAttack, 0.02f }, { p::ampDecay, 0.6f }, { p::ampSustain, 0.55f },
            { p::ampRelease, 0.5f }, { p::reverbMix, 0.35f }, { p::delayMix, 0.22f }, { p::polyphony, 12 },
            { p::master, -8.1f } } },
        { "Offbeat Bass", "TRANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.4f }, { p::subLevel, 0.6f },
            { p::cutoff, 520 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.1f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.14f }, { p::ampSustain, 0 }, { p::ampRelease, 0.08f }, { p::polyphony, 1 },
            { p::filterVel, 0.5f },
            { p::master, -3.3f } } },
        { "Psy Bass", "TRANCE", { { p::osc1Wave, 1 }, { p::subLevel, 0.85f }, { p::subWave, 1 },
            { p::cutoff, 300 }, { p::resonance, 0.15f }, { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.08f },
            { p::filtSustain, 0 }, { p::ampAttack, 0.002f }, { p::ampDecay, 0.12f }, { p::ampSustain, 0 },
            { p::ampRelease, 0.06f }, { p::polyphony, 1 }, { p::outputDrive, 5 }, { p::glide, 0.01f },
            { p::master, -7.2f } } },
        { "Trance Gate Keys", "TRANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.45f }, { p::osc2Level, 0.7f },
            { p::osc2Fine, 8 }, { p::cutoff, 4000 }, { p::lfoRate, 10 }, { p::lfoShape, 3 },
            { p::lfoToCutoff, 0.85f }, { p::ampSustain, 0.9f }, { p::ampRelease, 0.3f }, { p::delayMix, 0.25f },
            { p::polyphony, 10 },
            { p::master, -18.6f } } },
        { "Euphoric Lead", "TRANCE", { { p::osc2Level, 0.95f }, { p::osc2Semi, 7 }, { p::unisonCount, 5 },
            { p::unisonDetune, 18 }, { p::unisonSpread, 1 }, { p::cutoff, 6000 }, { p::filterEnvAmt, 0.25f },
            { p::ampAttack, 0.02f }, { p::ampRelease, 0.45f }, { p::polyphony, 1 }, { p::glide, 0.05f },
            { p::delayMix, 0.35f }, { p::delayFeedback, 0.5f }, { p::reverbMix, 0.35f },
            { p::master, 5.1f } } },
        { "Acid Roller", "TRANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.5f }, { p::cutoff, 600 },
            { p::resonance, 0.82f }, { p::filterEnvAmt, 0.8f }, { p::filtDecay, 0.16f }, { p::filtSustain, 0 },
            { p::filterDrive, 10 }, { p::keyTrack, 0.6f }, { p::polyphony, 1 }, { p::glide, 0.03f },
            { p::ampDecay, 0.25f }, { p::ampSustain, 0.1f }, { p::delayMix, 0.2f },
            { p::master, 2.3f } } },

        // ================= HOUSE =================
        { "Deep House Chord", "HOUSE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.42f }, { p::osc2Level, 0.7f },
            { p::osc2Fine, 7 }, { p::cutoff, 1600 }, { p::filterEnvAmt, 0.3f }, { p::filtDecay, 0.35f },
            { p::ampAttack, 0.015f }, { p::ampDecay, 0.5f }, { p::ampSustain, 0.3f }, { p::ampRelease, 0.4f },
            { p::chorusMix, 0.4f }, { p::reverbMix, 0.3f }, { p::polyphony, 10 }, { p::dnaWarmth, 0.7f },
            { p::master, -12.9f } } },
        { "Organ Stab", "HOUSE", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.7f }, { p::subWave, 1 }, { p::subLevel, 0.6f }, { p::cutoff, 5000 },
            { p::ampAttack, 0.004f }, { p::ampDecay, 0.25f }, { p::ampSustain, 0.15f }, { p::ampRelease, 0.12f },
            { p::mixerDrive, 2.5f }, { p::polyphony, 8 },
            { p::master, -19.9f } } },
        { "Filtered Disco Bass", "HOUSE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.6f }, { p::osc2Octave, -1 },
            { p::cutoff, 700 }, { p::resonance, 0.35f }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.2f },
            { p::lfoRate, 0.5f }, { p::lfoToCutoff, 0.3f }, { p::polyphony, 1 }, { p::ampRelease, 0.15f },
            { p::mixerDrive, 2.2f },
            { p::master, -3.8f } } },
        { "House Pluck", "HOUSE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.5f }, { p::osc2Semi, 12 },
            { p::cutoff, 2000 }, { p::resonance, 0.4f }, { p::filterEnvAmt, 0.75f }, { p::filtDecay, 0.08f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.18f }, { p::ampSustain, 0 }, { p::ampRelease, 0.15f },
            { p::delayMix, 0.28f }, { p::delayTime, 0.25f }, { p::reverbMix, 0.25f },
            { p::master, -8.9f } } },
        { "Jackin Bass", "HOUSE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.3f }, { p::subLevel, 0.65f },
            { p::cutoff, 450 }, { p::resonance, 0.3f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.12f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.2f }, { p::ampSustain, 0.05f }, { p::polyphony, 1 },
            { p::mixerDrive, 2.8f },
            { p::master, -3.9f } } },
        { "Warm Sub House", "HOUSE", { { p::osc1Wave, 3 }, { p::subLevel, 0.9f }, { p::subWave, 1 },
            { p::cutoff, 260 }, { p::filterEnvAmt, 0.2f }, { p::ampAttack, 0.01f }, { p::ampRelease, 0.2f },
            { p::polyphony, 1 }, { p::dnaWarmth, 0.85f }, { p::outputDrive, 2 },
            { p::master, -5.7f } } },
        { "French Filter Lead", "HOUSE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.85f }, { p::osc2Fine, 9 },
            { p::cutoff, 1200 }, { p::resonance, 0.45f }, { p::lfoRate, 0.25f }, { p::lfoToCutoff, 0.55f },
            { p::mixerDrive, 3.5f }, { p::ampSustain, 0.8f }, { p::ampRelease, 0.3f }, { p::polyphony, 6 },
            { p::outputDrive, 6 },
            { p::master, -22.6f } } },
        { "Garage Chord", "HOUSE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.55f }, { p::osc2Level, 0.65f },
            { p::osc2Fine, -8 }, { p::cutoff, 2400 }, { p::filterEnvAmt, 0.45f }, { p::filtDecay, 0.2f },
            { p::ampDecay, 0.35f }, { p::ampSustain, 0.2f }, { p::ampRelease, 0.25f }, { p::chorusMix, 0.3f },
            { p::delayMix, 0.2f }, { p::polyphony, 8 },
            { p::master, -14.9f } } },

        // ================= TECHNO =================
        { "Acid Screech", "TECHNO", { { p::osc1Wave, 1 }, { p::cutoff, 900 }, { p::resonance, 0.95f },
            { p::filterEnvAmt, 0.85f }, { p::filtDecay, 0.12f }, { p::filtSustain, 0 }, { p::filterDrive, 16 },
            { p::keyTrack, 0.8f }, { p::polyphony, 1 }, { p::glide, 0.025f }, { p::mixerDrive, 4 },
            { p::delayMix, 0.25f }, { p::delayFeedback, 0.5f },
            { p::master, 5.4f } } },
        { "Rumble Bass", "TECHNO", { { p::osc1Wave, 1 }, { p::osc1Octave, -1 }, { p::subLevel, 0.8f },
            { p::noiseLevel, 0.05f }, { p::cutoff, 200 }, { p::resonance, 0.2f }, { p::ampAttack, 0.02f },
            { p::ampSustain, 0.9f }, { p::ampRelease, 0.8f }, { p::reverbMix, 0.35f }, { p::reverbSize, 0.7f },
            { p::polyphony, 2 }, { p::outputDrive, 6 },
            { p::master, -12.9f } } },
        { "Industrial Stab", "TECHNO", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.2f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.8f }, { p::osc2Level, 0.9f }, { p::osc2Fine, -25 }, { p::cutoff, 1500 },
            { p::resonance, 0.5f }, { p::filterEnvAmt, 0.6f }, { p::filtDecay, 0.1f }, { p::ampDecay, 0.15f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.1f }, { p::mixerDrive, 5 }, { p::outputDrive, 8 },
            { p::master, -22.6f } } },
        { "Detroit Strings", "TECHNO", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.85f },
            { p::osc2Fine, 11 }, { p::cutoff, 2200 }, { p::resonance, 0.2f }, { p::ampAttack, 0.3f },
            { p::ampSustain, 0.8f }, { p::ampRelease, 0.9f }, { p::chorusMix, 0.5f }, { p::reverbMix, 0.4f },
            { p::polyphony, 8 }, { p::dnaAge, 0.6f },
            { p::master, -10.6f } } },
        { "Bleep Lead", "TECHNO", { { p::osc1Wave, 0 }, { p::osc2Wave, 2 }, { p::osc2Level, 0.4f },
            { p::osc2Octave, 1 }, { p::cutoff, 3000 }, { p::resonance, 0.3f }, { p::ampAttack, 0.003f },
            { p::ampDecay, 0.15f }, { p::ampSustain, 0.1f }, { p::ampRelease, 0.1f }, { p::polyphony, 1 },
            { p::delayMix, 0.3f }, { p::delayTime, 0.19f }, { p::delayFeedback, 0.55f },
            { p::master, 1.3f } } },
        { "Dark Drone Bass", "TECHNO", { { p::osc1Wave, 1 }, { p::osc1Octave, -2 }, { p::osc2Level, 0.6f },
            { p::osc2Fine, -14 }, { p::cutoff, 160 }, { p::resonance, 0.3f }, { p::ampAttack, 0.4f },
            { p::ampSustain, 1 }, { p::ampRelease, 1.5f }, { p::lfoRate, 0.15f }, { p::lfoToCutoff, 0.25f },
            { p::polyphony, 2 }, { p::outputDrive, 4 },
            { p::master, -12.5f } } },
        { "Hypnotic Arp", "TECHNO", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.35f }, { p::arpMode, 3 },
            { p::arpRate, 10 }, { p::arpOctaves, 2 }, { p::arpGate, 0.3f }, { p::cutoff, 1400 },
            { p::resonance, 0.55f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.09f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.12f }, { p::ampSustain, 0 }, { p::delayMix, 0.3f }, { p::delayFeedback, 0.6f },
            { p::master, -2.1f } } },
        { "Techno Zap", "TECHNO", { { p::osc1Wave, 1 }, { p::noiseLevel, 0.2f }, { p::cutoff, 5000 },
            { p::resonance, 0.6f }, { p::filterEnvAmt, -0.9f }, { p::filtDecay, 0.12f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.1f }, { p::ampSustain, 0 }, { p::ampRelease, 0.08f }, { p::polyphony, 4 },
            { p::reverbMix, 0.25f },
            { p::master, -2.1f } } },

        // ================= SYNTHWAVE =================
        { "Outrun Lead", "SYNTHWAVE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.9f }, { p::osc2Fine, 12 },
            { p::unisonCount, 3 }, { p::unisonDetune, 16 }, { p::cutoff, 3200 }, { p::filterEnvAmt, 0.3f },
            { p::ampAttack, 0.02f }, { p::ampRelease, 0.4f }, { p::delayMix, 0.35f }, { p::delayTime, 0.32f },
            { p::delayFeedback, 0.45f }, { p::reverbMix, 0.35f }, { p::polyphony, 1 }, { p::glide, 0.04f },
            { p::master, 4.3f } } },
        { "Retro Brass", "SYNTHWAVE", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.9f },
            { p::osc2Fine, -9 }, { p::cutoff, 1300 }, { p::filterEnvAmt, 0.55f }, { p::filtAttack, 0.07f },
            { p::filtDecay, 0.45f }, { p::filtSustain, 0.5f }, { p::ampAttack, 0.05f }, { p::ampRelease, 0.35f },
            { p::chorusMix, 0.3f }, { p::reverbMix, 0.3f }, { p::polyphony, 8 }, { p::dnaAge, 0.45f },
            { p::master, -12.7f } } },
        { "80s Poly Pad", "SYNTHWAVE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.5f }, { p::osc2Level, 0.8f },
            { p::osc2Fine, 10 }, { p::cutoff, 2400 }, { p::ampAttack, 0.6f }, { p::ampSustain, 0.9f },
            { p::ampRelease, 1.6f }, { p::chorusMix, 0.7f }, { p::reverbMix, 0.45f }, { p::reverbSize, 0.85f },
            { p::polyphony, 12 }, { p::dnaWarmth, 0.6f },
            { p::master, -16.9f } } },
        { "Neon Arp", "SYNTHWAVE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.4f }, { p::arpMode, 1 },
            { p::arpRate, 9 }, { p::arpOctaves, 2 }, { p::arpGate, 0.45f }, { p::cutoff, 2600 },
            { p::resonance, 0.3f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.12f }, { p::ampDecay, 0.18f },
            { p::ampSustain, 0 }, { p::delayMix, 0.35f }, { p::delayTime, 0.3f }, { p::reverbMix, 0.3f },
            { p::master, 1.0f } } },
        { "Chase Bass", "SYNTHWAVE", { { p::osc1Wave, 1 }, { p::subLevel, 0.6f }, { p::cutoff, 480 },
            { p::resonance, 0.3f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.15f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.2f }, { p::ampSustain, 0.1f }, { p::ampRelease, 0.12f }, { p::polyphony, 1 },
            { p::mixerDrive, 2.4f }, { p::character, 0.7f },
            { p::master, -3.3f } } },
        { "Nightdrive Keys", "SYNTHWAVE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.6f }, { p::osc2Level, 0.55f },
            { p::osc2Octave, 1 }, { p::cutoff, 3000 }, { p::filterEnvAmt, 0.35f }, { p::filtDecay, 0.4f },
            { p::ampDecay, 0.7f }, { p::ampSustain, 0.4f }, { p::ampRelease, 0.5f }, { p::chorusMix, 0.55f },
            { p::delayMix, 0.25f }, { p::reverbMix, 0.35f }, { p::polyphony, 8 },
            { p::master, -11.0f } } },
        { "Vice Lead", "SYNTHWAVE", { { p::osc1Wave, 3 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.6f },
            { p::osc2Fine, 8 }, { p::cutoff, 2800 }, { p::resonance, 0.25f }, { p::ampAttack, 0.05f },
            { p::ampRelease, 0.5f }, { p::lfoRate, 4.8f }, { p::lfoToPitch, 9 }, { p::polyphony, 1 },
            { p::glide, 0.06f }, { p::delayMix, 0.3f }, { p::reverbMix, 0.4f },
            { p::master, 2.7f } } },
        { "Retro Bell", "SYNTHWAVE", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Semi, 7 }, { p::osc2Level, 0 }, { p::osc2Fm, 0.32f }, { p::cutoff, 8000 },
            { p::ampDecay, 1.4f }, { p::ampSustain, 0.15f }, { p::ampRelease, 0.9f }, { p::chorusMix, 0.3f },
            { p::delayMix, 0.3f }, { p::reverbMix, 0.4f }, { p::polyphony, 10 },
            { p::master, -7.6f } } },
        { "Analog Horn", "SYNTHWAVE", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.45f },
            { p::osc2Level, 0.7f }, { p::cutoff, 1100 }, { p::filterEnvAmt, 0.5f }, { p::filtAttack, 0.1f },
            { p::filtDecay, 0.4f }, { p::filtSustain, 0.45f }, { p::ampAttack, 0.08f }, { p::ampRelease, 0.4f },
            { p::mixerDrive, 2.2f }, { p::polyphony, 6 }, { p::reverbMix, 0.28f },
            { p::master, -16.8f } } },
        { "Miami Pad", "SYNTHWAVE", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.55f },
            { p::osc2Level, 0.85f }, { p::osc2Fine, 13 }, { p::cutoff, 2000 }, { p::ampAttack, 0.8f },
            { p::ampSustain, 0.85f }, { p::ampRelease, 2 }, { p::chorusMix, 0.65f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.9f }, { p::polyphony, 12 }, { p::driftAmount, 3.5f },
            { p::master, -13.5f } } },

        // ================= CINEMA =================
        { "Deep Drone", "CINEMA", { { p::osc1Wave, 1 }, { p::osc1Octave, -2 }, { p::osc2Level, 0.7f },
            { p::osc2Fine, -18 }, { p::subLevel, 0.6f }, { p::cutoff, 320 }, { p::resonance, 0.2f },
            { p::ampAttack, 1.5f }, { p::ampSustain, 1 }, { p::ampRelease, 3 }, { p::lfoRate, 0.08f },
            { p::lfoToCutoff, 0.3f }, { p::reverbMix, 0.55f }, { p::reverbSize, 0.95f }, { p::polyphony, 6 },
            { p::master, -20.5f } } },
        { "Tension Pulse", "CINEMA", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.25f }, { p::cutoff, 800 },
            { p::resonance, 0.4f }, { p::lfoRate, 6 }, { p::lfoShape, 3 }, { p::lfoToCutoff, 0.6f },
            { p::ampAttack, 0.3f }, { p::ampSustain, 0.9f }, { p::ampRelease, 1.2f }, { p::reverbMix, 0.45f },
            { p::polyphony, 6 }, { p::driftAmount, 4 },
            { p::master, -13.3f } } },
        { "Sub Boom", "CINEMA", { { p::osc1Wave, 0 }, { p::osc1Octave, -2 }, { p::subLevel, 1 },
            { p::subWave, 1 }, { p::cutoff, 120 }, { p::filterEnvAmt, 0.4f }, { p::filtDecay, 0.8f },
            { p::ampAttack, 0.005f }, { p::ampDecay, 2.5f }, { p::ampSustain, 0 }, { p::ampRelease, 1.5f },
            { p::polyphony, 2 }, { p::outputDrive, 5 },
            { p::master, -13.6f } } },
        { "Glass Atmosphere", "CINEMA", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.18f }, { p::noiseLevel, 0.03f }, { p::cutoff, 5000 },
            { p::ampAttack, 1.8f }, { p::ampSustain, 0.8f }, { p::ampRelease, 3.5f }, { p::lfoRate, 0.12f },
            { p::lfoToCutoff, 0.25f }, { p::reverbMix, 0.65f }, { p::reverbSize, 1 }, { p::polyphony, 10 },
            { p::master, -18.5f } } },
        { "Slow Riser", "CINEMA", { { p::osc1Wave, 1 }, { p::noiseLevel, 0.15f }, { p::cutoff, 400 },
            { p::resonance, 0.5f }, { p::filterEnvAmt, 0.95f }, { p::filtAttack, 4 }, { p::filtSustain, 1 },
            { p::ampAttack, 1.5f }, { p::ampSustain, 1 }, { p::ampRelease, 1 }, { p::reverbMix, 0.5f },
            { p::polyphony, 4 },
            { p::master, -9.9f } } },
        { "Dark Strings", "CINEMA", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.9f },
            { p::osc2Fine, -12 }, { p::osc1Octave, -1 }, { p::cutoff, 1200 }, { p::resonance, 0.15f },
            { p::ampAttack, 0.7f }, { p::ampSustain, 0.9f }, { p::ampRelease, 1.8f }, { p::reverbMix, 0.5f },
            { p::reverbSize, 0.9f }, { p::polyphony, 10 }, { p::dnaWarmth, 0.7f },
            { p::master, -21.5f } } },
        { "Suspense Arp", "CINEMA", { { p::osc1Wave, 3 }, { p::arpMode, 4 }, { p::arpRate, 7 },
            { p::arpOctaves, 3 }, { p::arpGate, 0.35f }, { p::cutoff, 2000 }, { p::resonance, 0.35f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.1f }, { p::ampDecay, 0.2f }, { p::ampSustain, 0 },
            { p::delayMix, 0.35f }, { p::delayFeedback, 0.55f }, { p::reverbMix, 0.45f },
            { p::master, 3.5f } } },
        { "Voice Pad", "CINEMA", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.62f }, { p::osc2Wave, 3 },
            { p::osc2Level, 0.6f }, { p::osc2Fine, -7 }, { p::noiseLevel, 0.05f }, { p::cutoff, 1600 },
            { p::resonance, 0.3f }, { p::ampAttack, 1 }, { p::ampSustain, 0.9f }, { p::ampRelease, 2.4f },
            { p::chorusMix, 0.5f }, { p::reverbMix, 0.6f }, { p::reverbSize, 0.95f }, { p::polyphony, 10 },
            { p::master, -18.7f } } },

        // ================= SFX =================
        { "Riser", "SFX", { { p::osc1Wave, 1 }, { p::noiseLevel, 0.3f }, { p::cutoff, 300 },
            { p::resonance, 0.55f }, { p::filterEnvAmt, 1 }, { p::filtAttack, 3 }, { p::filtSustain, 1 },
            { p::lfoRate, 8 }, { p::lfoToPitch, 30 }, { p::ampAttack, 0.5f }, { p::ampSustain, 1 },
            { p::ampRelease, 0.3f }, { p::reverbMix, 0.4f }, { p::polyphony, 2 },
            { p::master, -7.2f } } },
        { "Downlifter", "SFX", { { p::osc1Wave, 1 }, { p::noiseLevel, 0.25f }, { p::cutoff, 6000 },
            { p::resonance, 0.5f }, { p::filterEnvAmt, -1 }, { p::filtDecay, 2.5f }, { p::filtSustain, 0 },
            { p::ampSustain, 0.9f }, { p::ampRelease, 0.6f }, { p::reverbMix, 0.45f }, { p::polyphony, 2 },
            { p::master, -4.8f } } },
        { "Laser Zap", "SFX", { { p::osc1Wave, 1 }, { p::cutoff, 4000 }, { p::resonance, 0.7f },
            { p::lfoRate, 18 }, { p::lfoToPitch, 80 }, { p::ampDecay, 0.18f }, { p::ampSustain, 0 },
            { p::ampRelease, 0.1f }, { p::filterEnvAmt, -0.6f }, { p::filtDecay, 0.15f }, { p::delayMix, 0.3f },
            { p::polyphony, 4 },
            { p::master, -2.9f } } },
        { "Wind Noise", "SFX", { { p::osc1Level, 0 }, { p::noiseLevel, 0.8f }, { p::cutoff, 900 },
            { p::resonance, 0.65f }, { p::lfoRate, 0.15f }, { p::lfoToCutoff, 0.7f }, { p::ampAttack, 1.5f },
            { p::ampSustain, 1 }, { p::ampRelease, 2 }, { p::reverbMix, 0.5f }, { p::polyphony, 2 },
            { p::master, -4.6f } } },
        { "Siren", "SFX", { { p::osc1Wave, 1 }, { p::cutoff, 3000 }, { p::resonance, 0.4f },
            { p::lfoRate, 0.6f }, { p::lfoShape, 1 }, { p::lfoToPitch, 100 }, { p::ampAttack, 0.05f },
            { p::ampSustain, 1 }, { p::ampRelease, 0.4f }, { p::polyphony, 1 }, { p::reverbMix, 0.3f },
            { p::master, -3.8f } } },
        { "Robot Talk", "SFX", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.2f }, { p::cutoff, 1200 },
            { p::resonance, 0.8f }, { p::lfoRate, 14 }, { p::lfoShape, 2 }, { p::lfoToCutoff, 0.8f },
            { p::ampSustain, 0.9f }, { p::ampRelease, 0.15f }, { p::polyphony, 2 }, { p::mixerDrive, 3 },
            { p::master, -9.7f } } },
        { "Space Sweep", "SFX", { { p::osc1Wave, 1 }, { p::osc2Level, 0.8f }, { p::osc2Fine, 25 },
            { p::cutoff, 700 }, { p::resonance, 0.75f }, { p::lfoRate, 0.1f }, { p::lfoToCutoff, 0.9f },
            { p::ampAttack, 0.8f }, { p::ampSustain, 1 }, { p::ampRelease, 2.5f }, { p::delayMix, 0.4f },
            { p::delayFeedback, 0.65f }, { p::reverbMix, 0.6f }, { p::reverbSize, 1 },
            { p::master, -16.4f } } },
        { "Impact Drone", "SFX", { { p::osc1Wave, 1 }, { p::osc1Octave, -2 }, { p::noiseLevel, 0.2f },
            { p::cutoff, 250 }, { p::resonance, 0.4f }, { p::ampAttack, 0.002f }, { p::ampDecay, 3 },
            { p::ampSustain, 0.2f }, { p::ampRelease, 2.5f }, { p::outputDrive, 8 }, { p::reverbMix, 0.6f },
            { p::reverbSize, 1 }, { p::polyphony, 3 },
            { p::master, -15.7f } } },

        // ================= extra staples =================
        { "Reese Bass", "BASS", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 0.95f },
            { p::osc2Fine, -22 }, { p::cutoff, 420 }, { p::resonance, 0.25f }, { p::ampSustain, 0.9f },
            { p::ampRelease, 0.2f }, { p::polyphony, 1 }, { p::mixerDrive, 3 }, { p::outputDrive, 4 },
            { p::glide, 0.02f },
            { p::master, -7.8f } } },
        { "Pluck Bass", "BASS", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.32f }, { p::subLevel, 0.5f },
            { p::cutoff, 800 }, { p::resonance, 0.4f }, { p::filterEnvAmt, 0.8f }, { p::filtDecay, 0.07f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.16f }, { p::ampSustain, 0 }, { p::ampRelease, 0.1f },
            { p::filterVel, 0.75f }, { p::polyphony, 2 },
            { p::master, -7.0f } } },
        { "Wobble Bass", "BASS", { { p::osc1Wave, 1 }, { p::osc2Level, 0.8f }, { p::osc2Fine, -16 },
            { p::subLevel, 0.7f }, { p::cutoff, 500 }, { p::resonance, 0.7f }, { p::lfoRate, 4 },
            { p::lfoShape, 1 }, { p::lfoToCutoff, 0.85f }, { p::polyphony, 1 }, { p::mixerDrive, 3.5f },
            { p::outputDrive, 5 },
            { p::master, -8.6f } } },
        { "Square Lead", "LEAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.5f }, { p::osc2Wave, 2 },
            { p::osc2Level, 0.5f }, { p::osc2Octave, -1 }, { p::cutoff, 2800 }, { p::resonance, 0.2f },
            { p::ampAttack, 0.01f }, { p::ampRelease, 0.25f }, { p::polyphony, 1 }, { p::glide, 0.03f },
            { p::delayMix, 0.25f }, { p::reverbMix, 0.2f },
            { p::master, -0.4f } } },
        { "Sync-Style Lead", "LEAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.15f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.85f }, { p::osc2Level, 0.85f }, { p::osc2Semi, 5 }, { p::cutoff, 3400 },
            { p::resonance, 0.45f }, { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.25f }, { p::polyphony, 1 },
            { p::mixerDrive, 3 }, { p::delayMix, 0.22f },
            { p::master, -1.6f } } },
        { "Clav Funk", "KEYS", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.22f }, { p::osc2Wave, 2 },
            { p::osc2Pw, 0.78f }, { p::osc2Level, 0.6f }, { p::cutoff, 3000 }, { p::resonance, 0.4f },
            { p::filterEnvAmt, 0.55f }, { p::filtDecay, 0.1f }, { p::filtSustain, 0 }, { p::ampDecay, 0.28f },
            { p::ampSustain, 0.05f }, { p::ampRelease, 0.12f }, { p::filterVel, 0.85f }, { p::polyphony, 8 },
            { p::master, -15.1f } } },
        { "Bell Piano", "KEYS", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.24f }, { p::subLevel, 0.3f }, { p::cutoff, 7000 },
            { p::ampDecay, 1.2f }, { p::ampSustain, 0.2f }, { p::ampRelease, 0.6f }, { p::filterVel, 0.6f },
            { p::reverbMix, 0.3f }, { p::polyphony, 12 },
            { p::master, -14.6f } } },
        { "Warm Analog Pad", "PAD", { { p::osc1Wave, 1 }, { p::osc2Wave, 3 }, { p::osc2Level, 0.7f },
            { p::osc2Fine, 6 }, { p::cutoff, 1400 }, { p::resonance, 0.15f }, { p::ampAttack, 1.2f },
            { p::ampSustain, 0.9f }, { p::ampRelease, 2.2f }, { p::chorusMix, 0.45f }, { p::reverbMix, 0.45f },
            { p::reverbSize, 0.85f }, { p::polyphony, 12 }, { p::dnaWarmth, 0.75f },
            { p::master, -15.6f } } },
        { "Evolving Pad", "PAD", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.4f }, { p::osc2Wave, 1 },
            { p::osc2Level, 0.75f }, { p::osc2Fine, -11 }, { p::cutoff, 900 }, { p::resonance, 0.35f },
            { p::lfoRate, 0.09f }, { p::lfoToCutoff, 0.55f }, { p::ampAttack, 1.6f }, { p::ampSustain, 0.9f },
            { p::ampRelease, 2.8f }, { p::reverbMix, 0.55f }, { p::reverbSize, 0.95f }, { p::polyphony, 10 },
            { p::master, -19.7f } } },
        { "Deep Space", "AMBIENT", { { p::osc1Wave, 0 }, { p::osc2Wave, 3 }, { p::osc2Level, 0.6f },
            { p::osc2Octave, -1 }, { p::osc2Fine, 9 }, { p::cutoff, 1100 }, { p::ampAttack, 2.5f },
            { p::ampSustain, 1 }, { p::ampRelease, 4 }, { p::lfoRate, 0.05f }, { p::lfoToCutoff, 0.4f },
            { p::delayMix, 0.35f }, { p::delayTime, 0.7f }, { p::delayFeedback, 0.6f }, { p::reverbMix, 0.7f },
            { p::reverbSize, 1 }, { p::polyphony, 8 },
            { p::master, -16.6f } } },
        { "Frozen Lake", "AMBIENT", { { p::osc1Wave, 0 }, { p::osc2Wave, 0 }, { p::osc2Octave, 2 },
            { p::osc2Level, 0 }, { p::osc2Fm, 0.12f }, { p::noiseLevel, 0.04f }, { p::cutoff, 3500 },
            { p::ampAttack, 2 }, { p::ampSustain, 0.85f }, { p::ampRelease, 4.5f }, { p::delayMix, 0.4f },
            { p::delayTime, 0.9f }, { p::delayFeedback, 0.65f }, { p::reverbMix, 0.75f }, { p::reverbSize, 1 },
            { p::polyphony, 10 }, { p::driftAmount, 2 },
            { p::master, -17.2f } } },

        // ================= DANCE (hypersaw/dance-station voicing) =================
        { "Hypersaw Anthem", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Level, 1 },
            { p::osc2Fine, 18 }, { p::unisonCount, 5 }, { p::unisonDetune, 34 }, { p::unisonSpread, 1 },
            { p::cutoff, 7000 }, { p::filterEnvAmt, 0.25f }, { p::ampAttack, 0.015f }, { p::ampSustain, 0.95f },
            { p::ampRelease, 0.5f }, { p::delayMix, 0.3f }, { p::delayTime, 0.375f }, { p::delayFeedback, 0.4f },
            { p::reverbMix, 0.35f }, { p::polyphony, 12 }, { p::master, -11.4f } } },
        { "Rave Pluck", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.9f }, { p::osc2Fine, 20 },
            { p::unisonCount, 4 }, { p::unisonDetune, 24 }, { p::cutoff, 4200 }, { p::resonance, 0.35f },
            { p::filterEnvAmt, 0.8f }, { p::filtDecay, 0.07f }, { p::filtSustain, 0 }, { p::ampDecay, 0.14f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.14f }, { p::delayMix, 0.35f }, { p::delayTime, 0.1875f },
            { p::delayFeedback, 0.5f }, { p::reverbMix, 0.3f },
            { p::master, -1.0f } } },
        { "Klub Lead", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.35f },
            { p::osc2Level, 0.85f }, { p::osc2Fine, -14 }, { p::unisonCount, 3 }, { p::unisonDetune, 20 },
            { p::cutoff, 5200 }, { p::resonance, 0.3f }, { p::mixerDrive, 3 }, { p::polyphony, 1 },
            { p::glide, 0.03f }, { p::ampRelease, 0.3f }, { p::delayMix, 0.28f }, { p::reverbMix, 0.25f },
            { p::master, 0.3f } } },
        { "Big Room Stab", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.95f }, { p::osc2Semi, 12 },
            { p::unisonCount, 4 }, { p::unisonDetune, 28 }, { p::cutoff, 3800 }, { p::filterEnvAmt, 0.6f },
            { p::filtDecay, 0.12f }, { p::filtSustain, 0 }, { p::ampDecay, 0.2f }, { p::ampSustain, 0 },
            { p::ampRelease, 0.18f }, { p::filterVel, 0.7f }, { p::outputDrive, 4 }, { p::polyphony, 10 },
            { p::master, -16.3f } } },
        { "Gate Chords", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.9f }, { p::osc2Fine, 15 },
            { p::unisonCount, 3 }, { p::unisonDetune, 22 }, { p::cutoff, 5000 }, { p::lfoRate, 12 },
            { p::lfoShape, 3 }, { p::lfoToCutoff, 0.9f }, { p::ampAttack, 0.008f }, { p::ampSustain, 0.95f },
            { p::ampRelease, 0.25f }, { p::reverbMix, 0.35f }, { p::polyphony, 12 },
            { p::master, -15.0f } } },
        { "Nu Trance Bass", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Wave, 2 }, { p::osc2Pw, 0.4f },
            { p::osc2Level, 0.55f }, { p::subLevel, 0.75f }, { p::cutoff, 460 }, { p::resonance, 0.28f },
            { p::filterEnvAmt, 0.5f }, { p::filtDecay, 0.13f }, { p::filtSustain, 0 }, { p::ampDecay, 0.18f },
            { p::ampSustain, 0 }, { p::ampRelease, 0.1f }, { p::polyphony, 1 }, { p::outputDrive, 4 },
            { p::master, -7.1f } } },
        { "Detuned Sweep", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.95f }, { p::osc2Fine, 24 },
            { p::unisonCount, 5 }, { p::unisonDetune, 40 }, { p::cutoff, 500 }, { p::resonance, 0.4f },
            { p::filterEnvAmt, 0.95f }, { p::filtAttack, 2.5f }, { p::filtSustain, 1 }, { p::ampAttack, 0.6f },
            { p::ampSustain, 0.95f }, { p::ampRelease, 1.2f }, { p::reverbMix, 0.45f }, { p::polyphony, 10 },
            { p::master, -10.0f } } },
        { "Festival Lead", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Wave, 1 }, { p::osc2Octave, 1 },
            { p::osc2Level, 0.8f }, { p::unisonCount, 5 }, { p::unisonDetune, 30 }, { p::unisonSpread, 0.95f },
            { p::cutoff, 8000 }, { p::ampAttack, 0.01f }, { p::ampRelease, 0.4f }, { p::polyphony, 1 },
            { p::glide, 0.02f }, { p::delayMix, 0.32f }, { p::delayFeedback, 0.45f }, { p::reverbMix, 0.4f },
            { p::master, 6.0f } } },
        { "Pumping Chords", "DANCE", { { p::osc1Wave, 1 }, { p::osc2Level, 0.9f }, { p::osc2Fine, 12 },
            { p::unisonCount, 3 }, { p::unisonDetune, 18 }, { p::cutoff, 3000 }, { p::lfoRate, 2.4f },
            { p::lfoShape, 2 }, { p::lfoToCutoff, 0.6f }, { p::ampAttack, 0.02f }, { p::ampSustain, 0.9f },
            { p::ampRelease, 0.35f }, { p::chorusMix, 0.3f }, { p::reverbMix, 0.35f }, { p::polyphony, 12 },
            { p::master, -11.9f } } },
        { "Pumping Pluck", "DANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.38f }, { p::osc2Level, 0.8f },
            { p::osc2Fine, 16 }, { p::unisonCount, 3 }, { p::unisonDetune, 16 }, { p::cutoff, 3200 },
            { p::resonance, 0.45f }, { p::filterEnvAmt, 0.75f }, { p::filtDecay, 0.09f }, { p::filtSustain, 0 },
            { p::ampDecay, 0.16f }, { p::ampSustain, 0 }, { p::delayMix, 0.3f }, { p::delayTime, 0.25f },
            { p::reverbMix, 0.28f },
            { p::master, -2.4f } } },
        { "Wide Vox Lead", "DANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.62f }, { p::osc2Wave, 1 },
            { p::osc2Level, 0.8f }, { p::osc2Fine, -12 }, { p::unisonCount, 3 }, { p::unisonDetune, 14 },
            { p::cutoff, 1500 }, { p::resonance, 0.6f }, { p::keyTrack, 0.9f }, { p::filterEnvAmt, 0.3f },
            { p::ampAttack, 0.04f }, { p::ampRelease, 0.4f }, { p::chorusMix, 0.4f }, { p::reverbMix, 0.4f },
            { p::polyphony, 6 },
            { p::master, -5.9f } } },
        { "Hard Dance Stab", "DANCE", { { p::osc1Wave, 2 }, { p::osc1Pw, 0.25f }, { p::osc2Wave, 1 },
            { p::osc2Level, 0.9f }, { p::osc2Fine, -20 }, { p::unisonCount, 4 }, { p::unisonDetune, 26 },
            { p::cutoff, 2600 }, { p::resonance, 0.5f }, { p::filterEnvAmt, 0.7f }, { p::filtDecay, 0.1f },
            { p::filtSustain, 0 }, { p::ampDecay, 0.18f }, { p::ampSustain, 0 }, { p::mixerDrive, 4 },
            { p::outputDrive, 6 }, { p::polyphony, 8 },
            { p::master, -19.3f } } },
    };
    return bank;
}

} // namespace sappsynth::presets
